<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Invite new user modal</name>
   <tag></tag>
   <elementGuidId>83ae0184-a670-4886-9f26-d74b04a5cc88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[(text() = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businesscreateOrganization Unit *Send InvitationCancel' or . = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businesscreateOrganization Unit *Send InvitationCancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel' or . = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>0b832ef2-cbd4-47c0-9eb2-32a570be2027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aab994d9-48dc-44b0-8927-1beba402271b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d3de8c4-4210-48c0-b95f-7eec40d60841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-102 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>992b3956-eafa-4d52-be94-68ea2f4274f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-1</value>
      <webElementGuid>f4f51043-358b-47cb-90d1-4b018b0cdcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>e944c991-b1d9-4b0a-861f-e7266cac884d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-1</value>
      <webElementGuid>667f632a-9d74-439a-b3dd-d11de5e4880f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel</value>
      <webElementGuid>0880d764-7e15-4a16-b019-35b8c16cbff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)</value>
      <webElementGuid>2f03fc5a-420e-4fa0-ba01-11ba4e4036f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']</value>
      <webElementGuid>c991cfe9-2574-4b98-ac03-783c51c5f05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-39']/mat-dialog-container</value>
      <webElementGuid>e1ea33c2-65a1-45a9-84c5-42649544677d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work'])[3]/following::mat-dialog-container[1]</value>
      <webElementGuid>5c2f9898-6e03-490e-bb24-5d56b253f0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto country'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>825ba586-9d20-4190-b529-65eb966ab9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>7b9f2b7c-864f-43e2-968a-41c92f7afa5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-1' and (text() = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel' or . = 'Invite New UserUserAdditional SettingsmailEmailaccount_circleFirst NameLast NamepersonRoleRole *businessOrganization UnitSend InvitationCancel')]</value>
      <webElementGuid>69dcbece-9ff6-46a3-9fda-e2660a145501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
