<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CoWorker</name>
   <tag></tag>
   <elementGuidId>c63a30ce-c471-4e03-bbf1-7b817e377768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class = 'mat-option-text' and (text() = ' Co-worker ' or . = ' Co-worker ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-20 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'mat-option-text' and (text() = ' CoWorker ' or . = ' CoWorker ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1984cd0e-6d88-4f7d-b22a-613e00e485a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>4d86cc14-ec1a-4ecc-bf07-2732c6d47ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CoWorker </value>
      <webElementGuid>d9e058fc-407f-4e5d-b0c6-b33a1bc52ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-20&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>ed0e6251-8e38-4a6e-8b3d-9d60c4d4a5dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-20']/span</value>
      <webElementGuid>04c24ed2-e4f8-4993-84ff-42b579855639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner'])[1]/following::span[1]</value>
      <webElementGuid>cdc09d64-bc3f-40ed-b4fb-3e4703a804f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[2]</value>
      <webElementGuid>72c68292-81bc-45ae-a33f-00b2851b356b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/preceding::span[1]</value>
      <webElementGuid>05d065fa-cca1-4cd3-b721-605af6209840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Quick Shortcuts'])[1]/preceding::span[2]</value>
      <webElementGuid>6061ff03-bd89-4731-8c42-63d91c8315fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CoWorker']/parent::*</value>
      <webElementGuid>a670a122-cd2d-4086-aef8-01b74f5b38d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>5c39450c-74ea-4eb6-a66f-745d9282acd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' CoWorker ' or . = ' CoWorker ')]</value>
      <webElementGuid>372b3404-96fb-460a-af69-20bb2d3377df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
