<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_reminder</name>
   <tag></tag>
   <elementGuidId>6b853b04-8eae-4d5a-9cad-40c1bb3eb76a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ag-grid-angular[@id='ezSignDocsGrid']/div/div/div/div[3]/div[2]/div/div/div/div[7]/ng-component/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-icon-button.mat-button-base.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f595b6d-6293-469f-8c27-37625c060472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-icon-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>a5422345-d34f-4ea9-998e-daaedcda4e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>scheduleicon</value>
      <webElementGuid>528beb4f-c1af-4627-be13-bbf04a592840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ezSignDocsGrid&quot;)/div[@class=&quot;ag-root-wrapper ag-layout-auto-height ag-ltr&quot;]/div[@class=&quot;ag-root-wrapper-body ag-layout-auto-height&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-auto-height ag-has-focus&quot;]/div[@class=&quot;ag-body-viewport ag-layout-auto-height ag-row-no-animation&quot;]/div[@class=&quot;ag-center-cols-clipper&quot;]/div[@class=&quot;ag-center-cols-viewport&quot;]/div[@class=&quot;ag-center-cols-container&quot;]/div[@class=&quot;ag-row ag-row-even ag-row-level-0 ezsign-history-grid ag-row-position-absolute ag-row-first ag-row-last ag-row-focus&quot;]/div[@class=&quot;ag-cell ag-cell-not-inline-editing ag-cell-with-height ag-cell-value ag-cell-focus&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator mat-icon-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>73766706-a6f6-4ff6-a9c5-7ae2efb1d352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ag-grid-angular[@id='ezSignDocsGrid']/div/div/div/div[3]/div[2]/div/div/div/div[7]/ng-component/button</value>
      <webElementGuid>bab47e07-c79d-41c2-a3f7-18acf3ead880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Modified'])[1]/following::button[5]</value>
      <webElementGuid>13e970ac-43b0-4f5f-83b0-25ed1198ba2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reminder'])[1]/following::button[5]</value>
      <webElementGuid>a626705f-7049-4aa1-b9ed-84323a46db0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELS2301031043'])[1]/preceding::button[1]</value>
      <webElementGuid>3556977c-4a4d-4ecd-bf6d-47193340c608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sample.pdf'])[1]/preceding::button[2]</value>
      <webElementGuid>bd1342c4-3785-4ade-9224-b661a69c4cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-component/button</value>
      <webElementGuid>5b67a940-3b5b-415e-b64c-e42f4de8e7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'scheduleicon' or . = 'scheduleicon')]</value>
      <webElementGuid>bf4a570c-a751-48cf-8c6a-c9407211aed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
