<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Receiver email address</name>
   <tag></tag>
   <elementGuidId>b4139a6e-57ed-4bdd-9819-df7b3bc7ba4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1d3f0a9-5c53-4cbe-87aa-87139d1a6813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>receiverEmailIdControl</value>
      <webElementGuid>ac0d77d1-c4d5-469e-9701-3922dfb1a8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c110-59 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>abdb2853-3b04-4d4e-8bf8-bba39a9be59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>receiverEmailIdControl</value>
      <webElementGuid>9d42866c-5d96-45ce-9e6f-b6c9466c4711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-12</value>
      <webElementGuid>4cafd9bd-3205-4b2c-96a6-351c0715c7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>112f95ee-eae0-44f4-944f-e01b6585520d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4c8a214-09bb-404b-a2db-5c5525a51e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-12&quot;)</value>
      <webElementGuid>30b2fc09-6a44-4257-a451-05109373903f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-12']</value>
      <webElementGuid>ddec8d0c-20d4-4c1c-8fcc-b210e0c87bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']/app-addupdatesigners/div/div/form/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>5c3bd75b-8816-4494-b28f-30964a7bf0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>f5d0b83e-cc25-44a8-a68b-11ee16602c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-12']</value>
      <webElementGuid>b3346cc8-cf16-4ceb-a58f-af7057475898</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
