<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_Email address is required</name>
   <tag></tag>
   <elementGuidId>93894c59-d43b-4068-b1d5-35042598356a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[text()=' Email address is required ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-error-5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-error[@role = 'alert' and (text() = ' Email address is required ' or . = ' Email address is required ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>44bc5de7-da9b-4627-86ab-73b380c244eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>e07d73eb-ff26-494c-945e-e3a2c143baf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error ng-tns-c110-70 ng-star-inserted</value>
      <webElementGuid>af99ef46-9b9b-48ea-a327-478ecf465367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-5</value>
      <webElementGuid>607de71d-e79a-445e-af9e-73c351e7f1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Email address is required </value>
      <webElementGuid>99413317-3af9-4749-85ad-4e3d56fe77ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-5&quot;)</value>
      <webElementGuid>c79faa53-3413-4891-a541-c94940a6917c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-5']</value>
      <webElementGuid>58ff9db1-204d-4ce5-826e-6096ca18d758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-addupdatesigners/div/div/form/mat-form-field[2]/div/div[2]/div/mat-error</value>
      <webElementGuid>58f0853e-06e9-41bc-aa99-6a114a5137d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receiver email address'])[1]/following::mat-error[1]</value>
      <webElementGuid>5f242a49-43d1-4aff-85d4-76635c455b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signer name is required'])[1]/following::mat-error[1]</value>
      <webElementGuid>9a286efc-f9dd-4d8c-a3f8-23a152255c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign here'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>b3f4f327-6a30-413e-b4f0-1fcfd89f02c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email address is required']/parent::*</value>
      <webElementGuid>97f2e3db-7231-464f-b4a1-13b123721581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div[2]/div/mat-error</value>
      <webElementGuid>d2b3f012-4bdd-431d-bc2b-62cf6b883acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-5' and (text() = ' Email address is required ' or . = ' Email address is required ')]</value>
      <webElementGuid>01d27270-ba1d-49f7-af78-3e15b54707bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
