<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_configureColumns</name>
   <tag></tag>
   <elementGuidId>b7e8aa11-7158-42ce-8e1f-221c3515ccbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.docicon.material-icons.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Configure Columns' or . = 'Configure Columns')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>a7fb4d72-1968-4e06-bbbd-cd766505676c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>31ce6845-2846-44ce-ba30-3ca36afe3710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Configure Columns</value>
      <webElementGuid>d22e2e1a-84ff-41f3-87e1-368a8f41ccca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate docicon material-icons mat-icon-no-color</value>
      <webElementGuid>da31bc57-5e4a-45c0-b65c-efcff3f8fea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b058d166-b43f-4fb4-98d6-8b031a9a6976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-message</name>
      <type>Main</type>
      <value>Configure Columns</value>
      <webElementGuid>657c9f03-1c7f-4f87-9c5e-b42ca97a25bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-240</value>
      <webElementGuid>168ee5a2-5f79-4ed5-a9d1-e424d6d8eda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>list_alt</value>
      <webElementGuid>da560eb5-6dc3-4731-8fbf-0bd1c5e9d0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-17-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-373 ng-trigger ng-trigger-translateTab&quot;]/app-ezsign-senderdocuments[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/table[@class=&quot;ng-star-inserted&quot;]/tr[1]/td[2]/div[@class=&quot;ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate docicon material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>99ae5982-3222-4402-b24f-139a750a1475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-17-0']/div/app-ezsign-senderdocuments/div/table/tr/td[2]/div/mat-icon</value>
      <webElementGuid>116fa835-9947-44b0-969f-44dd828ab92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure Columns'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>9bd8eb7c-bb83-4326-8a41-ef93451b106b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export CSV'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>ac9ab1a6-7b2d-4dd6-8974-4d6ec86cd6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='list_alt']/parent::*</value>
      <webElementGuid>6d2536b9-3243-45f8-b3e5-4174d1571720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/mat-icon</value>
      <webElementGuid>dd6c3a7f-20b6-4777-9d87-a547a1c86de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'list_alt' or . = 'list_alt')]</value>
      <webElementGuid>2087dc7c-c99b-4d9c-a14a-1ee874f53fc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
