<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_GG TESTER (testuser02mailinator.com)</name>
   <tag></tag>
   <elementGuidId>1053b7b1-14a1-4c3e-bd3f-2bc9219aeb9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//mat-option[@role='option'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>207011ec-db1c-4bcf-b803-083d76d5b9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2297acf9-3020-44db-9a06-031b75b14bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator ng-star-inserted</value>
      <webElementGuid>2e38ac32-2477-47fd-bf00-54d127579799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>2c6a0d88-fba1-4b67-acb4-5512c7</value>
      <webElementGuid>fd4d1d8e-354c-429c-be76-14b9b924db17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-12</value>
      <webElementGuid>840b87dd-302f-46d1-aeb0-faaf5f33c236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d9f6a3c5-5913-47ef-bfa9-6dfbf35cdb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ffd6468-fe7d-4567-b110-cf4e0afce4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> GG TESTER (testuser02@mailinator.com) </value>
      <webElementGuid>cc2b6f2f-0da9-41cf-a550-5fdb9f80e205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-12&quot;)</value>
      <webElementGuid>367ac8a4-2fce-48d4-a5c3-f49868f99525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-12']</value>
      <webElementGuid>a995bb04-e18f-4d50-b316-6c812242de8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-autocomplete-3']/mat-option</value>
      <webElementGuid>e208ab5e-eeb5-4ea9-a189-0a8feb557de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[1]/following::mat-option[1]</value>
      <webElementGuid>8a6bdf26-31b4-444d-9add-a4a7ab0b620f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GG tester 2 (norvs26@mailinator.com)'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>255b31b2-8204-48fa-9abb-dc5757db7a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option</value>
      <webElementGuid>42bf6b7d-2980-4ca5-9339-7318784882a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-12' and (text() = ' GG TESTER (testuser02@mailinator.com) ' or . = ' GG TESTER (testuser02@mailinator.com) ')]</value>
      <webElementGuid>c1676309-a85a-475b-b619-70d6a98ceb64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
