<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_expandAll</name>
   <tag></tag>
   <elementGuidId>b2745697-5f18-461d-852a-283406deedd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-icon[(text() = 'swap_horiz' or . = 'swap_horiz')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>ecd3d896-be16-45e8-837a-d09f7ec370cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>45d86649-f0f2-48d3-ac78-c3132e00c96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Expand All</value>
      <webElementGuid>9155e4e7-7b5d-4112-a98f-c9706592f9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate docicon material-icons mat-icon-no-color</value>
      <webElementGuid>3a2bdb8f-fc4e-47d2-9b81-92bd5db3a61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>326d2aa4-98d3-46ce-99fd-3006ba93b75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-message</name>
      <type>Main</type>
      <value>Expand All</value>
      <webElementGuid>494bbabb-b4d7-4c58-836c-1226ae9a5626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-242</value>
      <webElementGuid>5dec9815-f243-43cf-aa85-47be8203d362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swap_horiz</value>
      <webElementGuid>ee5ff2a7-3784-442b-be00-78fb6c559060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-17-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-373 ng-trigger ng-trigger-translateTab&quot;]/app-ezsign-senderdocuments[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/table[@class=&quot;ng-star-inserted&quot;]/tr[1]/td[2]/div[@class=&quot;ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate docicon material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>85f5221e-e4bc-4b8e-a6a0-832093584cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-17-0']/div/app-ezsign-senderdocuments/div/table/tr/td[2]/div/mat-icon[3]</value>
      <webElementGuid>407f72da-1e1e-47b9-809d-9a8601540e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export CSV'])[1]/following::mat-icon[1]</value>
      <webElementGuid>39d4c12a-6b5e-4a42-adc0-98bc835fec3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure Columns'])[1]/following::mat-icon[2]</value>
      <webElementGuid>ce73d6b5-5526-43c6-8dd5-dc81ca6fc6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand All'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>a05e3795-75be-48f3-be3e-cc3aadd4671e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refit'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>6fd41041-a763-4f3a-a2de-7d3f6def5e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='swap_horiz']/parent::*</value>
      <webElementGuid>35d43cfe-7819-4303-947f-78fe8c47d383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/mat-icon[3]</value>
      <webElementGuid>7719a8c0-a76f-4a55-8b3e-98fd998d8b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'swap_horiz' or . = 'swap_horiz')]</value>
      <webElementGuid>f8e1e317-7061-4bb9-b9c0-68d7852dd934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
