<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bold select</name>
   <tag></tag>
   <elementGuidId>df457051-d624-42bf-8c8b-7d2577d6f503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@title = 'Bold']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ngx-toggle-command[@ng-reflect-toolbar-item='bold']//div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.NgxEditor__MenuItem--IconContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>85be87ce-b95e-4234-9783-e45277068ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NgxEditor__MenuItem--IconContainer</value>
      <webElementGuid>5ba8509d-55f6-4c91-96f5-28dc11856d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bold</value>
      <webElementGuid>618310da-9d06-428c-b7b2-c5bcc022c60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c479-5 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c479-5 mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;wrapper&quot;]/app-teams[@class=&quot;ng-tns-c694-59 ng-star-inserted&quot;]/section[@class=&quot;teams-section ng-tns-c694-59&quot;]/div[@class=&quot;ng-tns-c694-59&quot;]/app-channel[@class=&quot;ng-tns-c695-60 ng-tns-c694-59 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/section[@class=&quot;table-listing ng-tns-c695-60&quot;]/div[@class=&quot;ng-tns-c695-60 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c695-60&quot;]/div[@class=&quot;ng-tns-c695-60&quot;]/div[@class=&quot;ng-tns-c695-60&quot;]/app-markdown-composer[@class=&quot;ng-tns-c695-60 ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator markdown-composer&quot;]/div[1]/div[1]/div[@class=&quot;NgxEditor__Wrapper&quot;]/ngx-editor-menu[1]/div[@class=&quot;NgxEditor__MenuBar&quot;]/ngx-toggle-command[@class=&quot;NgxEditor__MenuItem NgxEditor__MenuItem--Icon ng-star-inserted&quot;]/div[@class=&quot;NgxEditor__MenuItem--IconContainer&quot;]</value>
      <webElementGuid>dac45c25-8d8f-4df3-979e-470faa48c0ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[1]/following::div[10]</value>
      <webElementGuid>31ba00b5-5b05-4952-a842-f733ded21271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posts'])[1]/following::div[10]</value>
      <webElementGuid>40165751-66ab-484d-accd-b3fa823161de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Heading'])[1]/preceding::div[8]</value>
      <webElementGuid>0d0c3fdc-3429-40fd-8a33-3692b59dcf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results'])[1]/preceding::div[36]</value>
      <webElementGuid>9886d0ce-7590-4eb7-be09-217465152578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngx-toggle-command/div</value>
      <webElementGuid>93ccfade-5fbd-44ec-8509-606ed720a5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Bold']</value>
      <webElementGuid>84b2dfab-fffc-4c1d-ac2a-7e290b5f632f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
