<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_send</name>
   <tag></tag>
   <elementGuidId>05e2789a-00fa-4aae-8786-a1aff6f9d1b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-icon-button.mat-button-base.ng-star-inserted.post-send</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>918961c2-ce7f-4a3e-a0c1-7a77fc04deb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dab10a6b-5e1b-47d3-986b-7a345730de92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-icon-button mat-button-base ng-star-inserted post-send</value>
      <webElementGuid>d20cfbac-0b28-49b5-9fbd-74172eb75748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>post-send</value>
      <webElementGuid>9de40374-a26a-4441-a382-13013a7b778f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b31140c-0058-4781-b0fb-132e42962fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>send</value>
      <webElementGuid>e9009560-026e-4e41-870e-442f76af0d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c479-5 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c479-5 mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;wrapper&quot;]/app-teams[@class=&quot;ng-tns-c628-75 ng-star-inserted&quot;]/section[@class=&quot;teams-section ng-tns-c628-75&quot;]/div[@class=&quot;ng-tns-c628-75&quot;]/app-channel[@class=&quot;ng-tns-c629-92 ng-tns-c628-75 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/section[@class=&quot;table-listing ng-tns-c629-92&quot;]/div[@class=&quot;ng-tns-c629-92 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c629-92&quot;]/div[@class=&quot;ng-tns-c629-92&quot;]/div[@class=&quot;ng-tns-c629-92&quot;]/app-markdown-composer[@class=&quot;ng-tns-c629-92 ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator markdown-composer&quot;]/div[2]/div[@class=&quot;el-post-footer&quot;]/div[2]/button[@class=&quot;mat-focus-indicator mat-icon-button mat-button-base ng-star-inserted post-send&quot;]</value>
      <webElementGuid>7fcb8293-3a23-4450-afec-2adb054524d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[16]</value>
      <webElementGuid>a1300d79-d9f7-4ee9-be18-0387201d5078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Heading'])[1]/following::button[4]</value>
      <webElementGuid>c8adb5f0-a209-47c9-8591-af1f3cf220ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[1]/following::button[4]</value>
      <webElementGuid>be9a1666-e3c1-49bd-95ec-ddc8799f9bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results'])[1]/preceding::button[1]</value>
      <webElementGuid>12f63f10-885e-48b4-96c5-fd3dbaa4fc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Quick Shortcuts'])[1]/preceding::button[7]</value>
      <webElementGuid>e9ba86f4-93e1-475a-b536-46f0960ae802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card/div[2]/div/div[2]/button</value>
      <webElementGuid>4daaf552-c5d4-4291-933c-1db5a56e86c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'send' or . = 'send')]</value>
      <webElementGuid>2064bc68-e759-46a7-9b59-8b325811a796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
