<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Four</name>
   <tag></tag>
   <elementGuidId>c7997f17-df2e-4a1f-86ef-ea8837e097dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='postText']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#postText > h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0009a696-6647-4382-bd51-d7cb7d1def47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Four</value>
      <webElementGuid>ecd4c1b1-655f-4eaa-a93a-45e81a704f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postText&quot;)/h4[1]</value>
      <webElementGuid>9161aadf-8e6d-437a-9a19-afd97fe0b39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postText']/h4</value>
      <webElementGuid>6ff2aa3e-34f2-47ab-800e-96fa81872882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/following::h4[1]</value>
      <webElementGuid>679933e1-6b15-4dc0-a534-0a36487796f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[1]/preceding::h4[1]</value>
      <webElementGuid>843f8bc8-5e32-4495-abda-eda794fc0444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Results'])[1]/preceding::h4[1]</value>
      <webElementGuid>10e5b443-1d00-40bd-980e-c46ae5df6928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Four']/parent::*</value>
      <webElementGuid>622503b1-ec1e-45cd-944d-66230780d520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//read-more/div/h4</value>
      <webElementGuid>0f66e88c-2431-4284-a651-d9d6d8471448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Four' or . = 'Four')]</value>
      <webElementGuid>61364d14-b707-43eb-8fd8-3a564d15c2fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
