<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Underline</name>
   <tag></tag>
   <elementGuidId>7f6fe978-33c8-4ad3-a72a-562ab0392366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='postText']/p/u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>12207d9a-e991-4ce2-b6c5-ae9f228e22cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Underline</value>
      <webElementGuid>409df821-145d-4fba-8562-5d98a22730d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c479-5 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c479-5 mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;wrapper&quot;]/app-teams[@class=&quot;ng-tns-c694-59 ng-star-inserted&quot;]/section[@class=&quot;teams-section ng-tns-c694-59&quot;]/div[@class=&quot;ng-tns-c694-59&quot;]/app-channel[@class=&quot;ng-tns-c695-60 ng-tns-c694-59 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/section[@class=&quot;table-listing ng-tns-c695-60&quot;]/div[@class=&quot;ng-tns-c695-60 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c695-60&quot;]/div[@class=&quot;ng-tns-c695-60&quot;]/perfect-scrollbar[@class=&quot;post-perfect-scrollbar ng-tns-c695-60 ng-star-inserted&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/div[@class=&quot;ng-tns-c695-60 ng-star-inserted&quot;]/el-post[@class=&quot;ng-tns-c695-60 ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator el-post user-post-highlight&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/p[@class=&quot;post-content ng-star-inserted&quot;]/read-more[1]/div[@id=&quot;postText&quot;]/p[1]/u[1]</value>
      <webElementGuid>c50a322c-ea7a-4dc5-8daf-5a4d9e5ce503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postText']/p/u</value>
      <webElementGuid>e6c1ba2b-14e0-47ed-98e6-139720e3e248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/following::u[1]</value>
      <webElementGuid>b57550be-6744-439a-9036-b02b703700f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[1]/preceding::u[1]</value>
      <webElementGuid>dded7d66-256d-4adc-b411-a0268a87ffc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Underline']/parent::*</value>
      <webElementGuid>1cf506e1-1f41-4fee-a88b-63ad5d665b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>6922c619-d3a8-4d7a-995a-8c315eda7d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'Underline' or . = 'Underline')]</value>
      <webElementGuid>9178d9c4-66cb-46e5-bac6-e7646b959945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
