<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Delete Organization Unit</name>
   <tag></tag>
   <elementGuidId>166f9d4d-dd3f-4ec6-9556-b502629a0a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='mat-dialog-title-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-16</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h4[@class = 'mat-dialog-title' and (text() = 'Delete Organization Unit' or . = 'Delete Organization Unit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>2be3db7b-3059-4195-8315-2116ba9600c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>0aa9a5fa-de26-4562-9b74-a1a0d69c0406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-16</value>
      <webElementGuid>849e5169-08ce-4058-bc05-448c7965b326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Organization Unit</value>
      <webElementGuid>b41c64be-a48b-4132-81cb-09fe613dc494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-16&quot;)</value>
      <webElementGuid>5dbea328-daeb-460d-8289-4063ab18290f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-16']</value>
      <webElementGuid>f346e6d6-7675-488a-a316-95a04e4c6d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-16']/app-dialog-delete-ou/section/h4</value>
      <webElementGuid>fa6985e9-358d-4a7a-9890-326f089d674c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Organization Unit'])[1]/following::h4[1]</value>
      <webElementGuid>a903cd1c-2e1f-4f81-9514-d42fc0869a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Request Link'])[1]/following::h4[1]</value>
      <webElementGuid>13137fd7-b3ff-4606-b8c7-16a00f5697e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning! All resources associated with this root organization will be permanently deleted.'])[1]/preceding::h4[1]</value>
      <webElementGuid>733b72b5-b5fd-4768-95fb-0b293eb787e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete Organization Unit']/parent::*</value>
      <webElementGuid>f0210ca4-1035-4a14-8781-ec53eba11cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/h4</value>
      <webElementGuid>2ac3ac9b-acd4-4ba7-b6e4-2e4f0b2b7d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-16' and (text() = 'Delete Organization Unit' or . = 'Delete Organization Unit')]</value>
      <webElementGuid>8da42946-901e-4013-ba4f-63e7ee80da10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
