<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Edit Organization Unit modal</name>
   <tag></tag>
   <elementGuidId>e3890961-a27b-4fe6-8640-cb98a5a49fd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-15']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-15</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Edit Organization UnitOrganization Unit Name *SaveCancel' or . = 'Edit Organization UnitOrganization Unit Name *SaveCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>a77cc369-0efa-4a3f-8d4e-c8a66a284f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5de7026d-639b-4409-afbb-83e2cb5abc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04274d08-d5f8-4daa-94db-90884fde4d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-129 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>011842b4-13ae-4212-8507-a6e134d0c0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-15</value>
      <webElementGuid>8d1930fa-fd15-40a2-95ac-f294acb1a7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>2cab39b3-eb03-454a-9bf3-0dc078f22a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-15</value>
      <webElementGuid>b908124c-97db-46ce-a337-5520bd006050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Organization UnitOrganization Unit Name *SaveCancel</value>
      <webElementGuid>7d4f8a91-c3b0-4ed8-931d-e78769127dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-15&quot;)</value>
      <webElementGuid>5fb1b977-7a9f-4550-9a86-ff35e922ce9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-15']</value>
      <webElementGuid>cc85f1fd-bd38-47d1-b296-5bcc8006632a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-30']/mat-dialog-container</value>
      <webElementGuid>95a06eac-d311-4b61-8dea-d4d0f9e9ab72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Organization Unit'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>0908f6a0-4d7b-46d1-95f8-6cf83ac11bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Request Link'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>d4152e27-63b5-4a87-a785-274fbee7898d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>268a41a7-df21-4a90-b799-28770aec9aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-15' and (text() = 'Edit Organization UnitOrganization Unit Name *SaveCancel' or . = 'Edit Organization UnitOrganization Unit Name *SaveCancel')]</value>
      <webElementGuid>39df64a2-4eaf-4602-bdb1-63c5f3477f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
