<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Edit 2FA Phone Number</name>
   <tag></tag>
   <elementGuidId>eb5d52d9-b555-4f25-ae38-aecc7e7c8cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='mat-dialog-title-14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>5267c00a-8d8a-4a80-a102-784f2ed020c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>2ccef64b-8ab4-4ad3-88fa-237f347dd34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-14</value>
      <webElementGuid>3d17bfac-8bee-473d-a142-ef8f78080768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit 2FA Phone Number</value>
      <webElementGuid>6af72365-d554-4f22-9a25-3f7e20c3c311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-14&quot;)</value>
      <webElementGuid>9b96c2d6-c59c-4ce7-9618-cc3ebd6d26d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-14']</value>
      <webElementGuid>cd53fe78-2f9e-458a-adfe-4e9d9e2ca60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-12']/app-dialog-2fa-phone/section/form/h4</value>
      <webElementGuid>1a8ec266-0a20-486a-91e3-0e5225e1459a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::h4[1]</value>
      <webElementGuid>201ae3ea-b143-4860-aa77-aa062ee147f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::h4[1]</value>
      <webElementGuid>2eda1399-1c21-455f-bebb-abcbf4927907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/preceding::h4[1]</value>
      <webElementGuid>f610eb50-682e-4ee6-82ce-4a8db9b9fc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter a valid phone number'])[1]/preceding::h4[1]</value>
      <webElementGuid>c4fb3ff8-97e8-489e-bd8c-2480f54b553c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit 2FA Phone Number']/parent::*</value>
      <webElementGuid>b0a7b398-b52e-4525-8ad7-d6a2774cefe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/h4</value>
      <webElementGuid>fe36141c-7576-4e74-888a-2eab3d9af34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-14' and (text() = 'Edit 2FA Phone Number' or . = 'Edit 2FA Phone Number')]</value>
      <webElementGuid>bcdc2c9e-c4e1-491e-bfe1-75ff8fdfe5c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
