<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add new contact modal</name>
   <tag></tag>
   <elementGuidId>10f45516-4a04-4025-afc9-fc501341d1eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel' or . = 'Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>557669cf-8860-4a0c-a5b3-cae0861b1bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1c5704ed-bb56-4a1c-9944-a1c3db92fe1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c483ce75-d168-451a-8246-98f61a71168b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-211 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>25dd322f-1aca-42bf-be53-01e7e8c2dacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-8</value>
      <webElementGuid>6e3b5267-488b-4784-bd7f-f92a3e5386e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>852224e1-a476-4686-b8d1-09c9dd787b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-8</value>
      <webElementGuid>c092f795-e793-4803-be65-a10548ef13f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel</value>
      <webElementGuid>4cf11bb0-a38d-4d18-bca3-4e7dfa5b057b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-8&quot;)</value>
      <webElementGuid>54269c8d-62f7-422a-bbd9-40f43b9c4ac1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-8']</value>
      <webElementGuid>d9e936ef-0326-4f7d-ab5e-c8523efe7f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-44']/mat-dialog-container</value>
      <webElementGuid>059e9a6e-04c1-46f4-893b-313911846346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>90ba38c3-2421-4256-9bc3-2a60e81ee43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='autotester01@mailinator.com'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>82171b8c-3c84-4cdc-b3dc-0949d114c660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>88d738f9-660f-43b8-bd7a-d928f9789685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-8' and (text() = 'Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel' or . = 'Add New ContactFirst Name *Last Name * mail TypeEmailremove_circle_outline phone Type+1remove_circle_outlineAddress:add_circle_outlineCompanyPositionSelect Labels...NotesCreateCancel')]</value>
      <webElementGuid>926137f2-5576-4c28-9c82-508bf50e527f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
