<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type_email</name>
   <tag></tag>
   <elementGuidId>6544d56d-e9b6-441a-a286-c2d4b65d41c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@data-placeholder='Email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'email' and @name = 'email' and @placeholder = 'Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-163</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bedcc73-6ad8-467c-9027-e9223587ffce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>53885639-ccc2-4112-854b-b226a49110c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9dedc4ba-cad5-40cb-a938-c0390e158854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>245</value>
      <webElementGuid>b4ca0f66-1609-4bda-94ec-6bb49f45a3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c238-307 cdk-text-field-autofill-monitored ng-pristine ng-valid ng-touched</value>
      <webElementGuid>64fb5b39-9672-4076-b5d5-765a92e3da44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>245</value>
      <webElementGuid>7d2f1011-5629-44eb-9f38-fee56bd95715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f8906e9f-7e23-4e28-8a74-397d2c9aefd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>43058aae-6a43-495d-97c8-c79e138239db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>36f078ad-c96c-418c-adab-b0d17cc168ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-163</value>
      <webElementGuid>5661e089-752c-474e-8da1-b9ba52c45065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>4a1a81bd-e63d-4d1b-88a7-c70fb9fc803b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c524960-38a4-441b-9358-2532e8ae6f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06b39b04-432a-42ed-a615-05b261438a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-163&quot;)</value>
      <webElementGuid>8eb4eb4b-343a-4cfc-961a-3d53b9dbdd92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-163']</value>
      <webElementGuid>8b8458a9-a8ee-4a82-abfd-ac521cf8c2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-16']/app-dialog-add-contact/section/form/div/perfect-scrollbar/div/div/div/div/input-contact-email/mat-list/mat-list-item/div/div[3]/span/mat-form-field[2]/div/div/div/input</value>
      <webElementGuid>039cbab4-c1d5-45ee-abef-3596f023ffa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/mat-form-field[2]/div/div/div/input</value>
      <webElementGuid>7c15be98-6c20-4e17-89be-b8a5f3476506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'mat-input-163' and @placeholder = 'Email']</value>
      <webElementGuid>2f2b27ff-7735-4079-b3d3-752594c09309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
