<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Members dialog box</name>
   <tag></tag>
   <elementGuidId>3ab9621d-43bb-4d0b-a29d-a4404be3805b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Add TeamSettingsMembersEnter name/group to invite here INVITE searchFind existing member of this teamcancel Name  arrow_upward  Org Role  arrow_upward  Member Type  arrow_upward   GG TESTER Owner Owner Row per page: 1-1 of 1skip_previousnavigate_beforenavigate_nextskip_nextCreateCancel' or . = 'Add TeamSettingsMembersEnter name/group to invite here INVITE searchFind existing member of this teamcancel Name  arrow_upward  Org Role  arrow_upward  Member Type  arrow_upward   GG TESTER Owner Owner Row per page: 1-1 of 1skip_previousnavigate_beforenavigate_nextskip_nextCreateCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>de53461e-082d-4df9-acec-f341fd10aff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bd1eec63-0de5-4e90-9d90-e252a3b81346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f7ca5a9-2118-4046-a423-7d054609a46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-31 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>bd296e04-2c03-4eb5-accf-c236dbaf6ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>2ca7a6d8-9c51-46a0-b629-cf34380c72ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>476882e4-b37c-4e34-a17b-7d97cc9ef052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-1</value>
      <webElementGuid>fdc6a698-2b23-4331-89cd-e706d97ccc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add TeamSettingsMembersEnter name/group to invite here INVITE searchFind existing member of this teamcancel Name  arrow_upward  Org Role  arrow_upward  Member Type  arrow_upward   GG TESTER Owner Owner Row per page: 1-1 of 1skip_previousnavigate_beforenavigate_nextskip_nextCreateCancel</value>
      <webElementGuid>2a285f5c-8793-460f-94c4-502fd0dd386f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>2afd1fe9-8cf0-48ee-a37e-2492e54ffdc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>bf9643d4-ebf0-490f-ba4a-35969613d3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/mat-dialog-container</value>
      <webElementGuid>a30a924e-2d84-4e5d-a419-696367c8c392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Team'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>ec521960-d35c-434f-95c6-d25f9dcdca13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Teams'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>134266f9-73ed-4b66-a904-c969e4f838cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>5203f2c6-c6b1-4ae1-b28f-d2ee02371441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Add TeamSettingsMembersEnter name/group to invite here INVITE searchFind existing member of this teamcancel Name  arrow_upward  Org Role  arrow_upward  Member Type  arrow_upward   GG TESTER Owner Owner Row per page: 1-1 of 1skip_previousnavigate_beforenavigate_nextskip_nextCreateCancel' or . = 'Add TeamSettingsMembersEnter name/group to invite here INVITE searchFind existing member of this teamcancel Name  arrow_upward  Org Role  arrow_upward  Member Type  arrow_upward   GG TESTER Owner Owner Row per page: 1-1 of 1skip_previousnavigate_beforenavigate_nextskip_nextCreateCancel')]</value>
      <webElementGuid>9f474b9b-b4aa-4fe2-8361-15df5ce630c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
