<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Import CSV File modal</name>
   <tag></tag>
   <elementGuidId>0c1f5373-1fe4-452a-8010-a57fc37b556e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel' or . = 'Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>623c5b44-e1ac-4d7c-8b57-5fd6ad198faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a6cbec7f-b72e-4fcc-b232-c971538455f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fd4c4c8b-d566-4e53-b010-7340ebf60eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-60 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>63e725d8-b5a3-4962-bd24-9fe9f98bfacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-2</value>
      <webElementGuid>712ec170-ca0a-41fb-9e4e-7c359691f800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>3dd95885-9564-4c5f-b72e-9fb0dc4e3d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-2</value>
      <webElementGuid>83a63949-44e5-420d-9b02-b99c0ecc02dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel</value>
      <webElementGuid>d3b01ff2-57e7-447e-bedc-7cecb8b0e352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-2&quot;)</value>
      <webElementGuid>8498334f-b593-4ed9-abb1-410b26b1558d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']</value>
      <webElementGuid>f41f274c-b5c9-4bbe-90a0-e61baf99beba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/mat-dialog-container</value>
      <webElementGuid>f67e23a8-8336-476c-8891-04b7c13364e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-2', '&quot;', ')')])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>99c48d41-f692-4a40-a701-569a7348dad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::mat-dialog-container[1]</value>
      <webElementGuid>d79b58fc-de2d-4cb0-9451-c5a8e44fc332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>10aff598-48d1-4dad-b0ef-ca57b7423557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-2' and (text() = 'Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel' or . = 'Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel')]</value>
      <webElementGuid>0a59d7dc-0aac-44a5-b7ec-900a01289b3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
