<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Import CSV file modal</name>
   <tag></tag>
   <elementGuidId>924c32d1-a39a-44ec-a2d2-b35d529aabf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='cdk-overlay-pane']//mat-dialog-container[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel' or . = 'Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>cbcb22cc-baee-4cbe-8a9c-caafa9237722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e6193370-c47f-44c7-a641-101c7b4858f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>11548435-ff4a-4106-8ae6-3d719e8cb556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-75 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>2a080feb-2d8b-4a0f-be1f-c7a87ed2b086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-4</value>
      <webElementGuid>3b717191-941d-4178-a937-ffbb0003eebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>5a39ccad-6620-4034-9d4f-a3a9c0e86d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-4</value>
      <webElementGuid>d550ba43-8b83-4ad5-a3a5-82269af3616c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel</value>
      <webElementGuid>7a4b17e7-0afe-42fd-9082-27ea64920fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-4&quot;)</value>
      <webElementGuid>c2dffda3-cdfe-43a6-87a5-f65f92811004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-4']</value>
      <webElementGuid>1e1ea6c0-88bb-4e2d-9cff-8c41f1220f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-8']/mat-dialog-container</value>
      <webElementGuid>9f1d8dd9-9a39-4330-a831-762f7778e3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-4', '&quot;', ')')])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>a9c66c25-6651-4eb6-b99c-14233b2d07c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::mat-dialog-container[1]</value>
      <webElementGuid>273e9fe6-164c-4803-96b4-c587e620198b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>04d06cd7-b967-4739-b03c-d3e4f7bf3731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-4' and (text() = 'Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel' or . = 'Import CSV FileNeed a CSV template? Download it here . Choose File No file chosen createImporting Organization Unit *ImportCancel')]</value>
      <webElementGuid>249a116a-07e9-4d4c-9afa-711744ed6eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
