<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Profile</name>
   <tag></tag>
   <elementGuidId>edb9b839-b579-4836-b074-503df3dc2ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-tab-label-0-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-tab-label-0-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@role = 'tab' and (text() = 'Profile' or . = 'Profile')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c82ec4c5-77fd-4c7b-8833-57b541d127c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5fb62e27-db8d-4ef5-9b79-e84f5d841de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-ripple mat-tab-label mat-focus-indicator mat-tab-label-active ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>82184937-7dd2-4e9e-8ae1-7839ab4fe970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-tab-label-0-0</value>
      <webElementGuid>ff1f7525-256b-4800-91cb-d0d64ab591cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9919028f-5840-4deb-8012-239b8a685400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0e472229-942a-4eed-9c48-5837515eba68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bb573802-2e6c-448b-b38a-d5776708728f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c0928430-fc28-4817-9f46-d74dce710178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mat-tab-content-0-0</value>
      <webElementGuid>17ede54f-c5ec-4501-b6ec-260e36e7079e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9ea6981f-5000-4374-a7a9-c8325e89c1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25345b5d-242c-4af6-a18e-1631928cb6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>91b17dd6-0081-4e45-98a5-1e399cbc6288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-label-0-0&quot;)</value>
      <webElementGuid>67542283-a6e1-478b-9853-8b6a8fbda068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-0-0']</value>
      <webElementGuid>29b28627-b4ce-471c-aba8-29e7fea5893e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GG TESTER'])[1]/following::div[9]</value>
      <webElementGuid>fd9f5310-b7b3-4745-a0e3-d8cef2537357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::div[11]</value>
      <webElementGuid>059d9417-cdc7-49d7-b675-53200ab51108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/preceding::div[2]</value>
      <webElementGuid>df4ef3b6-097f-4d01-bf8b-c609c10eec9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>62011c66-ec79-4dd9-8a66-fa507cd799fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-tab-label-0-0' and (text() = 'Profile' or . = 'Profile')]</value>
      <webElementGuid>4cfcf9ee-4c8c-402c-9f72-260d382f715a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
