<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization number</name>
   <tag></tag>
   <elementGuidId>41c550e9-e0b5-40a1-91f3-a624622a86f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@ng-reflect-placeholder = 'Organization Number' and @placeholder = 'Organization Number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Organization Number' or . = 'Organization Number')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5270dc5a-2488-4fa5-b982-1d6700586906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c110-40 cdk-text-field-autofill-monitored ng-untouched ng-pristine</value>
      <webElementGuid>93eb2a58-43f7-4e3d-a6d6-7a2567441641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-placeholder</name>
      <type>Main</type>
      <value>Organization Number</value>
      <webElementGuid>05bba5ef-612a-46a3-9210-422f13204ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>60000275</value>
      <webElementGuid>ada038dd-923e-4e9e-9462-b01e7aed7c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-5</value>
      <webElementGuid>c7bbac5b-77af-4f20-8fa3-c2648af77f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Organization Number</value>
      <webElementGuid>6e211b65-7af5-48f4-ac7c-bfa3acd6f3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5977de90-0f75-473b-bcf7-975035714874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f01af355-cbdf-4a6f-915e-e3eb5255f6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-5&quot;)</value>
      <webElementGuid>5e5561d3-0113-4542-9f7e-30e4d363a7d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-5']</value>
      <webElementGuid>2ef8ac68-1945-4497-9dd9-3ee21ee55142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/section/div/mat-card/mat-card-content/div[3]/mat-form-field/div/div/div/input</value>
      <webElementGuid>582dcb02-9949-444f-b058-6a346a27c85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-form-field/div/div/div/input</value>
      <webElementGuid>44a09d00-2fc8-42ea-b310-a3de9d4705a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-5' and @placeholder = 'Organization Number']</value>
      <webElementGuid>ce62f507-1c46-4672-94b6-4d1ca85966be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
