<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-card_Tools</name>
   <tag></tag>
   <elementGuidId>c73f59a4-54da-4d86-921a-fa4739eca3bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-2-1']/div/section[3]/div/mat-card</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-card[(text() = ' Tools  Enable or disable tools by clicking on the toggle. ELNet ELSign EL HealthCheck Income and Expense PDF Converter ' or . = ' Tools  Enable or disable tools by clicking on the toggle. ELNet ELSign EL HealthCheck Income and Expense PDF Converter ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-card</value>
      <webElementGuid>e8bcfe08-dc43-4039-a38c-eb05e18623c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-card mat-focus-indicator ng-tns-c588-62</value>
      <webElementGuid>b0da09e3-9e17-4bae-9369-cd033b71d8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tools  Enable or disable tools by clicking on the toggle. ELNet ELSign EL HealthCheck Income and Expense PDF Converter </value>
      <webElementGuid>671aacf4-1071-407f-a03d-1eaba583b57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-2-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-78 ng-trigger ng-trigger-translateTab&quot;]/section[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c588-62&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator ng-tns-c588-62&quot;]</value>
      <webElementGuid>97dfa986-20ff-4f84-9d14-996734a2c258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-1']/div/section[3]/div/mat-card</value>
      <webElementGuid>f2a76ad0-ae2d-4d79-8fce-945039fa3b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By enabling this option, all join requests via URL will be automatically approved.'])[1]/following::mat-card[1]</value>
      <webElementGuid>adce94ec-2039-4e3e-a79f-8526370ec669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Auto Approve'])[1]/following::mat-card[1]</value>
      <webElementGuid>d6570816-4d01-424e-a888-c11a28aed0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/mat-card</value>
      <webElementGuid>c91f463e-58b1-40d6-9379-25b1b33d65f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-card[(text() = ' Tools  Enable or disable tools by clicking on the toggle. ELNet ELSign EL HealthCheck Income and Expense PDF Converter ' or . = ' Tools  Enable or disable tools by clicking on the toggle. ELNet ELSign EL HealthCheck Income and Expense PDF Converter ')]</value>
      <webElementGuid>e6930c93-95b9-45db-8081-a4dc7d6fcfae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
