<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_EL Sign</name>
   <tag></tag>
   <elementGuidId>95ef23ac-9827-4708-9d25-a90cc5f429b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[@for='mat-slide-toggle-6-input']//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5ce8470c-7653-4d91-93cc-df9fc0f8f994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665647145977</value>
      <webElementGuid>5b2ac001-b8d2-4fe8-acf3-fb30118fc9db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
