<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_EL HealthCheck</name>
   <tag></tag>
   <elementGuidId>bc8dfb75-b4a5-4a5c-9124-8521e74d720d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[@for='mat-slide-toggle-7-input']//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>eed57559-9e52-47c9-9771-f257edf9334b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665647178393</value>
      <webElementGuid>bb79b693-267a-4f1e-b488-0906d6bce147</webElementGuid>
   </webElementProperties>
</WebElementEntity>
