<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add my org modal 3</name>
   <tag></tag>
   <elementGuidId>13fbbed9-0655-402a-a7f4-0743dbd90af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Add My OrganizationOrganization Name *Organization Alias *.everleagues.comOther Service BusinessService Industry * Free Limited Planopen_in_newUsage limit Pay-As-You-Go Planopen_in_newPricing detailPaymentName on CardCard numberExpirationCVCZip / Postal CodeOrganization AddressStreetCityZip / Postal CodeState/ProvinceCountry Check here to indicate that you have read and agree to the Everleagues Software as a service (SaaS) subscription agreementBackCreate Cancel' or . = 'Add My OrganizationOrganization Name *Organization Alias *.everleagues.comOther Service BusinessService Industry * Free Limited Planopen_in_newUsage limit Pay-As-You-Go Planopen_in_newPricing detailPaymentName on CardCard numberExpirationCVCZip / Postal CodeOrganization AddressStreetCityZip / Postal CodeState/ProvinceCountry Check here to indicate that you have read and agree to the Everleagues Software as a service (SaaS) subscription agreementBackCreate Cancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>839f2a55-7b85-4940-a095-999f971e3230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>53c891ab-5d27-42b0-80f9-a595db66b7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fcc17f7a-0e0f-4210-ac63-782e0643bbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-85 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>c6a22882-29db-477c-8215-5c5d6e252873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-5</value>
      <webElementGuid>a41e118f-63e9-47f0-83db-149d269137fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>a4ec981e-0b1a-4909-ac3d-e2cb71b0fec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-5</value>
      <webElementGuid>a962af54-e742-424b-a6e6-198fccd839d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add My OrganizationOrganization Name *Organization Alias *.everleagues.comOther Service BusinessService Industry * Free Limited Planopen_in_newUsage limit Pay-As-You-Go Planopen_in_newPricing detailPaymentName on CardCard numberExpirationCVCZip / Postal CodeOrganization AddressStreetCityZip / Postal CodeState/ProvinceCountry Check here to indicate that you have read and agree to the Everleagues Software as a service (SaaS) subscription agreementBackCreate Cancel</value>
      <webElementGuid>299de763-4887-4327-91bc-9393d2114eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-5&quot;)</value>
      <webElementGuid>f85f443e-b25d-4302-afd7-5163ab1a93c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-5']</value>
      <webElementGuid>d2b23ce2-7cb3-44a1-b0d2-a36e43e093b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-6']/mat-dialog-container</value>
      <webElementGuid>da7b8659-ea01-4110-b79e-40c007f102a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>cf4e71d4-7e6e-4ec6-b62e-8a79db9f7ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-5' and (text() = 'Add My OrganizationOrganization Name *Organization Alias *.everleagues.comOther Service BusinessService Industry * Free Limited Planopen_in_newUsage limit Pay-As-You-Go Planopen_in_newPricing detailPaymentName on CardCard numberExpirationCVCZip / Postal CodeOrganization AddressStreetCityZip / Postal CodeState/ProvinceCountry Check here to indicate that you have read and agree to the Everleagues Software as a service (SaaS) subscription agreementBackCreate Cancel' or . = 'Add My OrganizationOrganization Name *Organization Alias *.everleagues.comOther Service BusinessService Industry * Free Limited Planopen_in_newUsage limit Pay-As-You-Go Planopen_in_newPricing detailPaymentName on CardCard numberExpirationCVCZip / Postal CodeOrganization AddressStreetCityZip / Postal CodeState/ProvinceCountry Check here to indicate that you have read and agree to the Everleagues Software as a service (SaaS) subscription agreementBackCreate Cancel')]</value>
      <webElementGuid>d13ebeab-4ddd-4125-81de-4144dadbae12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
