<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add New Contact modal</name>
   <tag></tag>
   <elementGuidId>a2bee127-a013-420e-929d-ad52c476692c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//mat-dialog-container[@role='dialog'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-20</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Add New ContactFirst Name *Last NameCreateCancel' or . = 'Add New ContactFirst Name *Last NameCreateCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>2d7fa47c-2bd5-4d62-855c-c6c86d223a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>dd8b89cd-5465-4c93-9a43-fa90256502d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80a8efd7-ed75-4114-8815-85625011a239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-187 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>71f167b6-05de-4a34-9eab-6c2a0c22f984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-20</value>
      <webElementGuid>e821ad99-366c-4a63-828a-791797cd7717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>3256dd73-17ab-414a-8067-ab7ad2650885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-20</value>
      <webElementGuid>edbabee4-f195-4f28-b170-df4cf7dda59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New ContactFirst Name *Last NameCreateCancel</value>
      <webElementGuid>deea4b31-7fd3-4595-8b9d-838aff46f6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-20&quot;)</value>
      <webElementGuid>39291c15-49e6-42bf-81b7-d0f561ed3b6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-20']</value>
      <webElementGuid>1258dc7d-12f2-4206-a77f-16f2db154b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-44']/mat-dialog-container</value>
      <webElementGuid>f273de65-2a92-4d84-b46a-806fdab0527d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>2c42ad64-1858-4682-9540-a101f94995da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>e70158b2-7c76-40f5-ada1-09f6552a0af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/mat-dialog-container</value>
      <webElementGuid>decd1383-a453-420b-8470-9a87334889b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-20' and (text() = 'Add New ContactFirst Name *Last NameCreateCancel' or . = 'Add New ContactFirst Name *Last NameCreateCancel')]</value>
      <webElementGuid>ebe2e892-97b7-46b0-916f-82e5f7dc852f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
