<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Add New Circle Association</name>
   <tag></tag>
   <elementGuidId>e46736d7-bb64-42ef-b621-bc9de654f2c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='mat-dialog-title-11']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h4[@class = 'mat-dialog-title' and (text() = 'Add New Circle Association' or . = 'Add New Circle Association')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>4526ca4f-f20e-4e55-80ed-8db05d05abb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>313439f8-146a-46cc-833b-b9da920092d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-11</value>
      <webElementGuid>e78d764f-f6bf-4531-882b-db3137b28b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Circle Association</value>
      <webElementGuid>7042b571-3866-415f-a5da-c92410a4d90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-11&quot;)</value>
      <webElementGuid>4204a0fd-1b04-4fc7-83ec-1e7819a3c959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-11']</value>
      <webElementGuid>a0433556-7952-4642-a039-466beec3dd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-11']/app-dialog-add-circle/section/form/h4</value>
      <webElementGuid>9893c608-da11-4a7b-b4f7-4d2442799d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 0'])[1]/following::h4[1]</value>
      <webElementGuid>50260955-acfc-49d8-859e-7c3fcbefc36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row per page:'])[1]/following::h4[1]</value>
      <webElementGuid>fef62d0e-d97f-4633-96cb-042393eb3d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/preceding::h4[1]</value>
      <webElementGuid>7a302769-7357-459a-82d5-a2a2c61b3ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User'])[2]/preceding::h4[1]</value>
      <webElementGuid>c4206764-c587-4041-b0b7-6c75d1b94dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add New Circle Association']/parent::*</value>
      <webElementGuid>ae56c4ed-fe51-4f53-a92c-ae7f39c407af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/h4</value>
      <webElementGuid>205b7b99-ee19-4291-b300-00da0a287c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-11' and (text() = 'Add New Circle Association' or . = 'Add New Circle Association')]</value>
      <webElementGuid>3342549f-27a7-47f1-9ec2-2bfba97a310e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
