<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Required_uploadfilecontainer</name>
   <tag></tag>
   <elementGuidId>3581c4bd-3b1e-450a-ac5f-3a0fc898c7ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.uploadfilecontainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-21']/app-iet-addreceipt/div/div/form/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34c59255-172a-440f-a3eb-3bf2dbdffb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uploadfilecontainer</value>
      <webElementGuid>633d7796-8705-45b3-903a-f0b963a01b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-21&quot;)/app-iet-addreceipt[@class=&quot;ng-star-inserted&quot;]/div[1]/div[@class=&quot;invgridColumn&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[1]/div[@class=&quot;uploadfilecontainer&quot;]</value>
      <webElementGuid>9c057719-6c25-4a99-a1a6-725b231b05d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-21']/app-iet-addreceipt/div/div/form/div/div</value>
      <webElementGuid>c09421a7-ee5d-4dbe-9fe9-57ea2f8f4ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Required'])[1]/following::div[1]</value>
      <webElementGuid>a4563996-2118-48f3-ab05-aed33e6f9cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a note'])[1]/preceding::div[10]</value>
      <webElementGuid>af5810e4-5cf2-44f4-bf85-fb1546b780be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[1]/preceding::div[17]</value>
      <webElementGuid>e538b988-362d-4be6-ad0f-faf60df8b30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>52a6dafa-2f3c-42b8-9203-4ee1a0265861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
