<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Add CompanyModal</name>
   <tag></tag>
   <elementGuidId>61101364-76df-4168-a139-e9fa3618f16d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Add CompanyclearCompany Name * Company name is required  Company Type *End of DecemberClosing Date *supervisor_accountShare With CANCEL            BEGIN play_circle_outline' or . = 'Add CompanyclearCompany Name * Company name is required  Company Type *End of DecemberClosing Date *supervisor_accountShare With CANCEL            BEGIN play_circle_outline')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-15</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>541fba15-d941-4d49-adc5-65b7349c16a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8b831f1a-7a72-4624-96df-c4996f82bbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cfd56277-fc2f-4f5f-8eac-c15d3941564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-151 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>efac613f-c658-4202-894e-936860465c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-15</value>
      <webElementGuid>a5e0bbf4-a9bb-4712-9d3d-7d62d76aadd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>9a9582d8-94bf-4531-8343-d248c407a521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add CompanyclearCompany Name * Company name is required  Company Type *End of DecemberClosing Date *supervisor_accountShare With CANCEL            BEGIN play_circle_outline</value>
      <webElementGuid>048e0a94-7e2b-4acc-9f70-0d0d3ae54cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-15&quot;)</value>
      <webElementGuid>884b31ef-4e54-448a-ac67-ad517819842b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-15']</value>
      <webElementGuid>04e795e0-05c1-4bd5-a29e-9c41431ac1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-40']/mat-dialog-container</value>
      <webElementGuid>bacbcc80-4599-4361-8d48-84491b06e590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>45cc039e-6661-4cb1-aa3a-cd5e0de22ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>1485cf61-3164-4f16-8232-7d769988e5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-15' and (text() = 'Add CompanyclearCompany Name * Company name is required  Company Type *End of DecemberClosing Date *supervisor_accountShare With CANCEL            BEGIN play_circle_outline' or . = 'Add CompanyclearCompany Name * Company name is required  Company Type *End of DecemberClosing Date *supervisor_accountShare With CANCEL            BEGIN play_circle_outline')]</value>
      <webElementGuid>7671bba1-4661-4939-a3a9-b8ab915db008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
