<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Edit CompanyModal</name>
   <tag></tag>
   <elementGuidId>2f0b17ab-627b-4afc-9b39-37a2345e6a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-25</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[@role = 'dialog' and (text() = 'Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     ' or . = 'Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>758f69c6-6006-4785-8caa-97bb40b125ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6ba975d5-806b-4af5-8704-ef243dcb991d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b89c5ea0-9756-4f77-89f6-a770bdfaf212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-266 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>5841578c-14fe-4a41-bf40-0508b77a36b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-25</value>
      <webElementGuid>6127fe9b-545e-4306-b688-1ae72bccaa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>736c4882-e405-4afd-ab0a-572f97dd661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     </value>
      <webElementGuid>35e8ecdc-e33b-47ca-9b99-92bfd1b349c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-25&quot;)</value>
      <webElementGuid>63a88c33-c1cb-447c-96be-17d14e3fe7ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-25']</value>
      <webElementGuid>1a4f035b-d304-4aa3-b84d-94062e0955f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-74']/mat-dialog-container</value>
      <webElementGuid>433501d1-d2f7-4b67-a1e1-ab6033809f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOV 2022'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>aec2a9fb-3435-4551-aaad-db4924aed23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPDATE'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>917e0962-25ae-4620-857b-36c8619972ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>b1dd5248-8a94-4e8f-a494-4f3066bd96e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-25' and (text() = 'Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     ' or . = 'Edit CompanyclearCompany Name*ConsultingCompany Type*End of DecemberClosing Date* GG tester 2 cancelsupervisor_accountShare WithCANCEL      UPDATE loop     ')]</value>
      <webElementGuid>46c2183f-adab-4a06-b63f-594e091232db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
