<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Add ReceiptModal</name>
   <tag></tag>
   <elementGuidId>6477ec23-2869-452f-ae54-f30e6062a3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='cdk-overlay-pane']//mat-dialog-container[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-19</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Add ReceiptclearVendor/Customer Name * Vendor name is required Account Type *Receipt Date *Amount *Upload Receipt *RequiredAdd a note CANCEL       Done check_circle_outline     ' or . = 'Add ReceiptclearVendor/Customer Name * Vendor name is required Account Type *Receipt Date *Amount *Upload Receipt *RequiredAdd a note CANCEL       Done check_circle_outline     ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>781643c8-f488-46c7-95ef-e983edd65463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8d33498d-e8ea-42c0-b960-e5e1c064edec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>71efd21e-a691-4d5e-92a7-a9de58c8ecf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-189 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>314cac1d-ee43-457c-b5bb-0212a1aa6b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-19</value>
      <webElementGuid>749c6fa5-2983-41a1-b7f4-efd6065750d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>a2f28866-f062-4f0e-8518-1014251646fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add ReceiptclearVendor/Customer Name * Vendor name is required Account Type *Receipt Date *Amount *Upload Receipt *RequiredAdd a note CANCEL       Done check_circle_outline     </value>
      <webElementGuid>fba3a561-bb21-4f5d-abbe-38ffeeaed0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-19&quot;)</value>
      <webElementGuid>c912187e-cc5b-4169-9fd0-4da323dbb197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-19']</value>
      <webElementGuid>76bd0daf-3a10-4490-a4ed-4f3c55095516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-56']/mat-dialog-container</value>
      <webElementGuid>bc131d60-673f-402a-b3fe-b3445dc5ee22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPDATE'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>13d6e809-11fa-451d-a5b9-7a339bb0e5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>0f2b253f-642c-47a0-8675-0d5bc3f91600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>ef25ba48-7687-4957-bcc3-c41f08ea1533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-19' and (text() = 'Add ReceiptclearVendor/Customer Name * Vendor name is required Account Type *Receipt Date *Amount *Upload Receipt *RequiredAdd a note CANCEL       Done check_circle_outline     ' or . = 'Add ReceiptclearVendor/Customer Name * Vendor name is required Account Type *Receipt Date *Amount *Upload Receipt *RequiredAdd a note CANCEL       Done check_circle_outline     ')]</value>
      <webElementGuid>ad0dbba9-87d4-4e2d-8ff8-1cac8d4fa77a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
