<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-hint_Required</name>
   <tag></tag>
   <elementGuidId>6941620c-b415-4c73-a91e-a7a46a77392f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-hint[text()='*Required']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-hint[@class = 'mat-hint' and (text() = '*Required' or . = '*Required')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-hint-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-hint</value>
      <webElementGuid>68c77a98-e0b0-41f5-b521-0dd79329a897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-hint</value>
      <webElementGuid>8cdb3003-6d6f-4c00-9500-a817a4f6bcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-hint-1</value>
      <webElementGuid>9b00ed4f-7003-40c0-ae13-2e3356582e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*Required</value>
      <webElementGuid>48919a0c-d1f0-461d-a9cd-f64317a3c4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-hint-1&quot;)</value>
      <webElementGuid>a09c1d50-0cc0-4e9e-a95b-b00ce4da1dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-hint[@id='mat-hint-1']</value>
      <webElementGuid>322291b0-3ad2-429e-8d5d-2bbf582b6bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-21']/app-iet-addreceipt/div/div/form/div/label/mat-hint</value>
      <webElementGuid>ed6c44bc-aaad-462f-b686-103c701a74d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receipt amount is required'])[1]/following::mat-hint[1]</value>
      <webElementGuid>c6d4d7f1-d801-4f47-a243-3a2c16d491ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a note'])[1]/preceding::mat-hint[1]</value>
      <webElementGuid>a44adddc-0811-479d-9ab9-de5c93f352c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[1]/preceding::mat-hint[1]</value>
      <webElementGuid>2c6fb270-efdd-46cf-942e-75e52612dff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='*Required']/parent::*</value>
      <webElementGuid>86849261-9d14-4719-a82a-6b210ef1a930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-hint</value>
      <webElementGuid>082901ce-8e24-4424-b11f-51b01fef7d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-hint[@id = 'mat-hint-1' and (text() = '*Required' or . = '*Required')]</value>
      <webElementGuid>c1181784-fe2e-4963-b1a5-fd960da54b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
