<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_react_like</name>
   <tag></tag>
   <elementGuidId>74884e75-7a8c-4cc4-9690-6608853b7da1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-button-toggle-15-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='reaction'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @name = 'reaction' and (text() = '👍' or . = '👍')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16d295b4-61e8-4167-9cc9-4668fd2240e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff5a57f4-f630-4ca3-9ade-de3db373e896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-toggle-button mat-focus-indicator</value>
      <webElementGuid>1d13edbb-461a-4204-9c4f-468630c0be30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-button-toggle-15-button</value>
      <webElementGuid>a9372cff-c325-4005-97b9-6706f85dd26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f7c7329-f3b6-435c-8a01-2f5ed6606502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c91e0f7-7378-44a3-813f-cc7661e4ae2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reaction</value>
      <webElementGuid>5d7479d8-2501-4d17-a97e-7bdd1fcba1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>👍</value>
      <webElementGuid>273e3459-3451-4a5c-9732-d9388780feb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-button-toggle-15-button&quot;)</value>
      <webElementGuid>1ef7f0f2-62bb-402d-b689-82e2e539b34a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mat-button-toggle-15-button']</value>
      <webElementGuid>a293d000-2902-40d7-8e9b-78328a7c77d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-button-toggle[@id='mat-button-toggle-15']/button</value>
      <webElementGuid>c2445013-7866-402c-a4df-96876b4e5f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Chat'])[1]/following::button[1]</value>
      <webElementGuid>8187bab8-ecfc-4eef-aef6-797938a303d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meet disabled for chatrooms larger than 30 participants'])[1]/following::button[1]</value>
      <webElementGuid>a111e4df-816b-44e4-80ca-7b014f35ec36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='💖'])[1]/preceding::button[1]</value>
      <webElementGuid>f982ad8c-2618-4e79-98be-6382725fe25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-button-toggle/button</value>
      <webElementGuid>af468a41-9e13-4a5c-aae8-c59d6d959fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mat-button-toggle-15-button' and @name = 'reaction' and (text() = '👍' or . = '👍')]</value>
      <webElementGuid>1fa80c00-5056-47dd-a42b-7becb6346b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
