<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_reply</name>
   <tag></tag>
   <elementGuidId>96537feb-3ea6-4a96-9f47-10e77bb94f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='add-area']//div)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e6be294a-23a4-42fe-ae80-3e02ca61d432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665999646082</value>
      <webElementGuid>1656f302-73cc-4c17-bbb3-f72c31499d7f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
