<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete label modal</name>
   <tag></tag>
   <elementGuidId>b225807b-a835-491f-add2-177065435008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[(text() = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel' or . = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-11</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel' or . = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>d5731124-be5c-4105-a9b8-6a7fe1d26ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0ad35419-d388-4751-8ae5-b5eeab58fec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc21ff94-a8e2-43cf-aff1-cfba71855393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-96 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>b48431ca-b0d8-4e4c-9ea9-ea110effa0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-11</value>
      <webElementGuid>7ded8431-c91f-4cc4-bc0e-bd54d7907778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>4204e9c4-14ed-475d-80b8-953ba5f7a3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-11</value>
      <webElementGuid>41d58a42-3035-4767-9fbf-402567036217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel</value>
      <webElementGuid>77281bdb-658f-416c-aa54-2f7f88bc05c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-11&quot;)</value>
      <webElementGuid>3b43b619-1560-4d6f-a9da-4845119e5a73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-11']</value>
      <webElementGuid>90525ee3-3b6e-48b9-8870-2cc80c175341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-27']/mat-dialog-container</value>
      <webElementGuid>89f27e2b-1ef9-421a-83a2-a169aa1bd23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 1'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>bc09c07c-6dd0-4d59-85b1-d90a33c82915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row per page:'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>4db51258-e808-4bca-8f6f-de447b818f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>a5177e4a-581b-47f2-8e4f-dde52c34a9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-11' and (text() = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel' or . = 'Delete Label Are you sure you want to delete Label QA Edit? Delete LabelCancel')]</value>
      <webElementGuid>fb3dbe82-c010-43c1-b73a-a76612523fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
