<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Label Name Field is required</name>
   <tag></tag>
   <elementGuidId>0ec08982-bef4-479d-81c8-79f530c9745c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-3']/app-dialog-add-label/section/form/div/div/mat-form-field/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-wrapper.ng-tns-c110-47</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c33cb316-1123-4fd5-9121-d37754a3470f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-wrapper ng-tns-c110-47</value>
      <webElementGuid>6387b439-689d-4d9d-9079-31feb75955f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Label Name *Field is required</value>
      <webElementGuid>25193dbb-ff4c-4bc9-ba02-680059c15165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-3&quot;)/app-dialog-add-label[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;dialog-container&quot;]/form[@class=&quot;ng-touched ng-dirty ng-invalid&quot;]/div[@class=&quot;mat-dialog-content&quot;]/div[1]/mat-form-field[@class=&quot;mat-form-field ng-tns-c110-47 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-touched ng-dirty mat-form-field-invalid ng-invalid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c110-47&quot;]</value>
      <webElementGuid>ad14c657-fdea-4bfc-876a-a3a42a6a2e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-dialog-add-label/section/form/div/div/mat-form-field/div</value>
      <webElementGuid>153502dc-a84e-4fdc-a3ad-9e3c11ae9ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Label'])[1]/following::div[3]</value>
      <webElementGuid>04a7ad13-e153-4867-948c-ca1970bd6572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 0'])[1]/following::div[30]</value>
      <webElementGuid>98597557-3c13-440a-b790-db470aa5176f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/mat-form-field/div</value>
      <webElementGuid>d4548404-d58a-4444-9a8b-cff665547ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Label Name *Field is required' or . = 'Label Name *Field is required')]</value>
      <webElementGuid>11d4ae24-1b96-4699-a0dd-7cf9b42ddc15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
