<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Add New Label</name>
   <tag></tag>
   <elementGuidId>fd3b3eb5-9197-456b-965a-c2b2e123f495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='mat-dialog-title-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>2a6cf9fa-b2c8-4551-8596-1c04f866727c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>2a9770de-3232-4ac6-8797-ea4c4cc0514d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-5</value>
      <webElementGuid>f61e5e5d-def1-4b6b-bfb4-91f47eb518d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Label</value>
      <webElementGuid>fbff9f5e-4334-49a6-959d-4c4bf3c88b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-5&quot;)</value>
      <webElementGuid>e062eb92-19c9-40a4-ac15-b82d61fe699a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-5']</value>
      <webElementGuid>db54dc8d-aa9f-40dd-8559-f8d648d3bb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-5']/app-dialog-add-label/section/form/h4</value>
      <webElementGuid>c2065ade-70bc-4a23-af2b-57f3ce5523b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 0'])[1]/following::h4[1]</value>
      <webElementGuid>7ee50fdc-a801-44d8-bf43-f46e8d4a23bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Row per page:'])[1]/following::h4[1]</value>
      <webElementGuid>9199a202-1627-4f81-b715-871a76a97bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label Name'])[1]/preceding::h4[1]</value>
      <webElementGuid>ccac6a10-1135-4dcf-93ed-477b06de7fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field is required'])[1]/preceding::h4[1]</value>
      <webElementGuid>23e4ca03-768c-45cd-b4de-a4e363b8bc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add New Label']/parent::*</value>
      <webElementGuid>4894ff48-cece-4420-9a82-d8a941e518e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/h4</value>
      <webElementGuid>c778158e-cfb8-4bde-92d4-e67bbe4f950e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-5' and (text() = 'Add New Label' or . = 'Add New Label')]</value>
      <webElementGuid>336592d1-981b-4a73-9d5d-38ef34812b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
