<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add New Label Name</name>
   <tag></tag>
   <elementGuidId>96dc3753-1a99-45a9-bcd1-88749a0d6b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'labelName' and @data-placeholder = 'Label Name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @placeholder = 'Label Name' and @name = 'labelName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f241fa4e-cbc6-46ff-abf2-bca7ef9271e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d7c05fe-fe99-400b-800b-936fba1693fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Label Name</value>
      <webElementGuid>cb363dba-0fa4-4775-90e8-1c329e9a0a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>labelName</value>
      <webElementGuid>2865182e-cb8b-45fb-af89-e193277149bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5b490275-bef1-4f1e-93fc-45223bba135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c110-47 cdk-text-field-autofill-monitored ng-touched ng-dirty ng-invalid</value>
      <webElementGuid>d812ca93-855f-44c1-a1a7-986fdaf20cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9b8a48d9-d85a-415e-8a29-7cb35c2301a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelName</value>
      <webElementGuid>d29c248b-9428-4a4a-a671-8ac0dcfbfa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2f34b18-0520-4432-ba49-a6ec162e41eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-placeholder</name>
      <type>Main</type>
      <value>Label Name</value>
      <webElementGuid>43d984f0-adcc-465d-a1ae-ec0ff62f2b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5451f5d-818d-4e10-a64f-4b9735c07f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-6</value>
      <webElementGuid>d81849c1-df26-4806-bd3a-f5e6456739e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fe4e119d-6adc-48ac-9b62-e567629abfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d4a2191-c515-4c8f-8a8d-655e27283b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-error-2</value>
      <webElementGuid>2d00e9fd-d957-4ec4-b6c6-333411c10cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-6&quot;)</value>
      <webElementGuid>c8fbc21d-1a1e-41c2-8921-db7b2ba2f7c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-6']</value>
      <webElementGuid>77970632-363f-402b-a5d3-2ef2f8da75e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-dialog-add-label/section/form/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>2701ad32-ef52-40f7-bf19-a66d9b67bcc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>2950d3c6-acc5-4a06-85c9-128a85f66d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Label Name' and @name = 'labelName' and @id = 'mat-input-6']</value>
      <webElementGuid>2411a8c0-5a57-4f2c-86fd-9df437af0cb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
