<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shared With Me</name>
   <tag></tag>
   <elementGuidId>8ac7ddc0-7b9b-4445-9262-13e000fa3d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mat-focus-indicator.ng-tns-c540-20.mat-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@routerlinkactive = 'active' and @href = '/main/storage/shared' and (text() = 'keyboard_arrow_rightShared With Me ' or . = 'keyboard_arrow_rightShared With Me ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(.,'keyboard_arrow_rightShared With Me')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93ad7167-1000-42f4-8df6-1364c4c1ee0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>91604850-236c-4389-a951-356ab497d7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator ng-tns-c540-20 mat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>969e2abf-2822-4332-b63e-218bd1b64f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>b3a6bdeb-41e5-43ff-84dd-46d1ef6e2dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>storage/shared</value>
      <webElementGuid>733033ec-0fdb-4c92-b013-bb56a18ba7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link-active-options</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>da9d22eb-9357-401a-ba8d-a14a00e1c0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4fcf8c42-cec3-4e9b-af51-27316781dac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f71da355-c401-420b-ac1c-bb3571376ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/main/storage/shared</value>
      <webElementGuid>81cfc4cf-f53e-45ea-990f-f548a594f8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>keyboard_arrow_rightShared With Me </value>
      <webElementGuid>83af2bbc-edc6-490b-a48b-ef5fb7f26dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c481-5 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c481-5 mat-drawer-transition mat-drawer-container-has-open&quot;]/mat-sidenav[@class=&quot;mat-drawer mat-sidenav left-sidenav ng-tns-c195-6 ng-trigger ng-trigger-transform mat-drawer-over ng-star-inserted mat-drawer-opened&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c195-6&quot;]/perfect-scrollbar[@class=&quot;perfect-scrollbar ng-tns-c481-5 ng-star-inserted&quot;]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/px-gdn-sidemenu[1]/ul[1]/px-gdn-sideitem[@class=&quot;ng-tns-c540-18 ng-star-inserted&quot;]/li[@class=&quot;ng-tns-c540-18 menu-level--1 open&quot;]/ul[@class=&quot;children ng-tns-c540-18 ng-trigger ng-trigger-closeState&quot;]/px-gdn-sideitem[@class=&quot;ng-tns-c540-20 ng-tns-c540-18 ng-star-inserted&quot;]/li[@class=&quot;ng-tns-c540-20 menu-level-0 close&quot;]/div[@class=&quot;item ng-tns-c540-20&quot;]/a[@class=&quot;mat-focus-indicator ng-tns-c540-20 mat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>c9c75f6d-babe-437f-8750-dfe9d221b903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Files'])[1]/following::a[1]</value>
      <webElementGuid>585b24b6-8783-44dd-b9da-73ef81d662a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_drop_down'])[4]/following::a[2]</value>
      <webElementGuid>a76a09a9-3273-4b79-9d97-3e0d8d738966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELSign'])[1]/preceding::a[1]</value>
      <webElementGuid>3c88f0ff-851d-4da1-aa79-7286d4065832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/main/storage/shared')]</value>
      <webElementGuid>39aafd83-5ffd-4d6b-97a9-d86dbc0a388b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//px-gdn-sideitem[8]/li/ul/px-gdn-sideitem[2]/li/div/a</value>
      <webElementGuid>d310b599-ca6e-4097-9894-6409e2031189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/main/storage/shared' and (text() = 'keyboard_arrow_rightShared With Me ' or . = 'keyboard_arrow_rightShared With Me ')]</value>
      <webElementGuid>42077834-3ce2-4340-8d07-d2367cd5f0e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
