<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_ShareFiles Modal</name>
   <tag></tag>
   <elementGuidId>8f2504f8-fcff-451b-91c7-5231600b58e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = 'Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save ' or . = 'Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@role='dialog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>827f21b4-3697-4c55-9025-f7356ac7f809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8d5e5ccc-dfb1-4cfd-bd6b-00879b31207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14958aa9-4478-4b47-93de-e0fcbc80ad25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-106 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>b8c0d29e-0e63-43ef-ba25-e3cd10fc991c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-12</value>
      <webElementGuid>b9120f4f-4761-4182-a7aa-76978ffe61ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>9a50d0da-45c7-402e-964b-8257322d68e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-12</value>
      <webElementGuid>a3234558-24e2-472d-b346-3761fb0d3891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save </value>
      <webElementGuid>171c6e83-7eeb-407c-bcfd-189d5c9e54b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-12&quot;)</value>
      <webElementGuid>8acaf9b6-1e12-41fd-882a-7bc8c8d1c9ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-12']</value>
      <webElementGuid>bce3fce8-fdde-4eb0-8662-a323d1e75ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-29']/mat-dialog-container</value>
      <webElementGuid>42df6609-ab33-4d1c-86ab-cf2dce880a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JPEG File'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>a1aed12d-268d-400e-a580-689b41b8a880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>8b9fee74-0364-4721-9e2e-015cf95e4b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>2e6f20d3-a904-4f13-8234-ec541caecd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-12' and (text() = 'Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save ' or . = 'Share Files closeAdd UsersViewer Notify users Shared withNot SharedCopy Share Link Save ')]</value>
      <webElementGuid>9cf45a97-0f2c-46ad-a679-b15d9a48db64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
