<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_DeleteConfirmationModalFolder</name>
   <tag></tag>
   <elementGuidId>a4caeca4-f352-493a-97e8-faad4eb305e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[(text() = ' Do you confirm the deletion of Automation folder EDIT file? ConfirmCancel' or . = ' Do you confirm the deletion of Automation folder EDIT file? ConfirmCancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-17</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container[(text() = ' Do you confirm the deletion of Automation folder file? ConfirmCancel' or . = ' Do you confirm the deletion of Automation folder file? ConfirmCancel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>81f468dd-70e8-43a1-96ec-9457b4c9759c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f19a974d-6713-4e31-8dcd-6f3e10a8e6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f4cf315a-49ee-47a0-be04-c02e3e0a7105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c31-219 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>1b53ad42-f91a-43c5-882e-3fc874716bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-17</value>
      <webElementGuid>9b8e869a-ecbd-45ed-b31d-5648e01af1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>6b51c0e8-2e81-4472-9c92-0a844d1eafcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-17</value>
      <webElementGuid>1e481ba2-0908-4cfe-a386-2d1f8ef10c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Do you confirm the deletion of Automation folder file? ConfirmCancel</value>
      <webElementGuid>7db27aef-baba-432b-93bd-4b2660e997e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-17&quot;)</value>
      <webElementGuid>4e576e9d-67c2-4d83-98a6-aebd56a5addc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-17']</value>
      <webElementGuid>0dd5ff78-3436-4a48-bb13-c9b269afb228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-47']/mat-dialog-container</value>
      <webElementGuid>6ba1e90a-58da-4d8b-ae5c-13d25d52bd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JPEG File'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>6d2ee9b6-4dee-4830-a217-b38a7f49880b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>615856fe-1cb6-4c48-9f7e-af7cbe43b2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>0a65c4e5-946d-4a80-a0f7-a6aa0e71bbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-17' and (text() = ' Do you confirm the deletion of Automation folder file? ConfirmCancel' or . = ' Do you confirm the deletion of Automation folder file? ConfirmCancel')]</value>
      <webElementGuid>816230f9-45ea-48bb-b91f-3ea5512691f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
