<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_warning</name>
   <tag></tag>
   <elementGuidId>17e503d3-ee4e-4596-8753-5adb090153f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='GG TESTER'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.warning-msg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f57f8957-ff8c-4618-bebb-4563d3ca0dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>warning-msg</value>
      <webElementGuid>a47d28c6-4b89-4b1d-b80b-780483d92482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> You should host an Open Meeting only when you need to include guests who are non EL members. It is a public meeting and therefore does not offer all the security features of a private group meeting. You may initiate a private group meeting from any chat group. </value>
      <webElementGuid>735c454c-5d00-424e-878b-805b47f338c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-page[@class=&quot;ng-tns-c481-0 ng-trigger ng-trigger-routerAnimation ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container ng-tns-c481-0&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;wrapper&quot;]/app-open-meet[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;open-meet-container&quot;]/div[@class=&quot;warning-container&quot;]/span[@class=&quot;warning-msg&quot;]</value>
      <webElementGuid>88a9166f-5414-470c-84d0-b779c7244f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GG TESTER'])[1]/following::span[1]</value>
      <webElementGuid>d673c360-e051-474d-a751-4e0deb3a0db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::span[2]</value>
      <webElementGuid>b64afdd3-055b-4450-bead-6ee1461cb2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meeting Title'])[1]/preceding::span[1]</value>
      <webElementGuid>f33b13b1-1683-441e-8cc1-3e059e41e0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You should host an Open Meeting only when you need to include guests who are non EL members. It is a public meeting and therefore does not offer all the security features of a private group meeting. You may initiate a private group meeting from any']/parent::*</value>
      <webElementGuid>9a10f0f3-cd7b-4fbf-8268-537aba1a0494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-open-meet/div/div/span</value>
      <webElementGuid>23a4bbb0-78e1-4e30-94fa-8b2c04ce38f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' You should host an Open Meeting only when you need to include guests who are non EL members. It is a public meeting and therefore does not offer all the security features of a private group meeting. You may initiate a private group meeting from any chat group. ' or . = ' You should host an Open Meeting only when you need to include guests who are non EL members. It is a public meeting and therefore does not offer all the security features of a private group meeting. You may initiate a private group meeting from any chat group. ')]</value>
      <webElementGuid>4d3e55e6-8f5f-4a7c-b3e1-e3ea8b36cc19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
