<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click here to join GG Automation on EverLeagues</name>
   <tag></tag>
   <elementGuidId>40d543d1-7fa4-430a-813c-af51f758d9b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Click here to join GG Automation on EverLeagues.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f2db6af-6271-419a-98b6-683f8b22281e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mailinator.com/linker?linkid=911b390e-e4bd-4be4-9333-e97a3b5c6aee</value>
      <webElementGuid>2e5cfcb8-6a37-426a-927b-dd71492172ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_other</value>
      <webElementGuid>832c99dd-63ea-4a48-908f-365019f3dab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>7796bb49-5b83-455f-87b9-44655c6192ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here to join GG Automation on EverLeagues.</value>
      <webElementGuid>cfbb32fd-364a-4208-aed8-8d765d2e386e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/h3[1]/a[1]</value>
      <webElementGuid>31e0c1d0-f320-4a2a-bc39-8bed8147e855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/09-Settings/Users/Co worker/iframe_-- HTML EMAIL BODY --</value>
      <webElementGuid>95aea722-fee4-4dfa-9e8b-c6e76dcad734</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Click here to join GG Automation on EverLeagues.')]</value>
      <webElementGuid>24a61fb1-2a28-4818-ba9b-4818dce8ae8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://app.everleagues.com/login'])[1]/preceding::a[1]</value>
      <webElementGuid>1006a434-b490-4ec5-a0d7-18d25b9b242a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.everleagues.com'])[1]/preceding::a[2]</value>
      <webElementGuid>e16f414c-a1d9-48d7-b2f3-260298ea8984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click here to join GG Automation on EverLeagues.']/parent::*</value>
      <webElementGuid>72391c46-f860-4ba2-a874-7a2cc0edb6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mailinator.com/linker?linkid=911b390e-e4bd-4be4-9333-e97a3b5c6aee')]</value>
      <webElementGuid>5b91d7a5-529e-438f-a1b5-e013d22314aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>f5ade885-0d1a-4444-9a7f-a3804ec1ab4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mailinator.com/linker?linkid=911b390e-e4bd-4be4-9333-e97a3b5c6aee' and (text() = 'Click here to join GG Automation on EverLeagues.' or . = 'Click here to join GG Automation on EverLeagues.')]</value>
      <webElementGuid>be8e1ab3-9693-40c2-a6fa-6cf2dc50c0ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
