<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_Password</name>
   <tag></tag>
   <elementGuidId>8db038df-0ec6-4d8f-a586-db3c5f1c81e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-error-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-error-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>0d9a4b9e-efc3-43fe-ae19-435e72457fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>aed11005-a671-4d1b-affd-dfe17ab9d719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error ng-tns-c110-1</value>
      <webElementGuid>140d8ba8-093b-42ad-9ad1-9045861eb74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-0</value>
      <webElementGuid>2400c535-a071-4ff6-9a09-f0548702b2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Password must be at least 8 characters with at least an uppercase, a lowercase and a number. </value>
      <webElementGuid>099e66ec-a97e-4687-be79-c53daa313112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-0&quot;)</value>
      <webElementGuid>80eb382b-d189-4abc-943d-7942ab8e2231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-0']</value>
      <webElementGuid>c2141303-a17f-4641-b57f-1d0bf5e6202e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::mat-error[1]</value>
      <webElementGuid>4db44bd5-fdc0-4cc5-9cb8-702a82d27367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::mat-error[1]</value>
      <webElementGuid>21483d26-209f-4cab-b0b5-a5e0a7013e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='terms and conditions.'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>54cc8eb7-230f-49a4-ad78-2dfb8f9333de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password must be at least 8 characters with at least an uppercase, a lowercase and a number.']/parent::*</value>
      <webElementGuid>dde873a0-1e3b-41e9-b113-dfe1b3702e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>ee5039b4-d943-48bd-aa7b-d86ac182ebe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-0' and (text() = ' Password must be at least 8 characters with at least an uppercase, a lowercase and a number. ' or . = ' Password must be at least 8 characters with at least an uppercase, a lowercase and a number. ')]</value>
      <webElementGuid>fa357ceb-2cf9-4c86-af0e-fa4efeaf08a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
