<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assigned Clients empty</name>
   <tag></tag>
   <elementGuidId>2cf9e21d-bf2f-4886-80c6-b2c3963c5609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/app-client-assign-by-employee/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>32297c8c-f199-48a5-be00-aeadf4b4ab5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c13d59af-b704-4ff3-9b53-8ee4ebfad23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>a788f8bd-5bf9-4696-9183-11ad292fed62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-container</value>
      <webElementGuid>2d86424d-6f37-4aea-9f94-acd91aa3d3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ffc3762a-60e4-4184-9afa-20bb6db3d6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>14096ba8-2d51-4d1a-bb88-e10d2a8f76ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Assigned Clients searchcancel</value>
      <webElementGuid>ae510f4e-f2a8-4ad3-9e2c-3da34551985e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-2-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-105 ng-trigger ng-trigger-translateTab&quot;]/app-client-assign-by-employee[@class=&quot;tab-container ng-star-inserted&quot;]/div[@class=&quot;white-container&quot;]</value>
      <webElementGuid>d5226d8d-5da6-442c-a4e4-f739a596d5cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/app-client-assign-by-employee/div[2]</value>
      <webElementGuid>0c7416dc-0d5e-402c-be84-4ea61246752e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GG tester 2'])[1]/following::div[5]</value>
      <webElementGuid>31427a1f-0724-4ed2-94f0-64af6ac1a4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GT'])[1]/following::div[6]</value>
      <webElementGuid>6fdef5fa-8181-41ab-9bfb-37f501c73e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-client-assign-by-employee/div[2]</value>
      <webElementGuid>949a9b76-2eec-4ad9-bf86-a6941d2462bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Assigned Clients searchcancel' or . = ' Assigned Clients searchcancel')]</value>
      <webElementGuid>a9598944-e7b8-4d2e-b584-5695ffa126f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
