<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clients column</name>
   <tag></tag>
   <elementGuidId>480e85ba-107d-4669-a536-661b0e363083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//mat-list-option[@ng-reflect-value='544e2801-2f6f-408c-b0de-fdb705']//div)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = ' Clients searchcancelGTGG Tester 3' or . = ' Clients searchcancelGTGG Tester 3')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d75b934-9dc6-4974-9a60-87b4250c6ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>649d090a-5e60-4e5c-a380-e1fbadac39dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>582f4f98-8d71-4793-ba43-98efeb771700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-container</value>
      <webElementGuid>312bb613-c2cc-49b7-abb1-779ebb23bb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4a734616-3777-434b-ac76-cceb9d8d6c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>251496fb-4194-4d83-bd54-4170d48a3839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Clients searchcancelGTGG Tester 3</value>
      <webElementGuid>d14b76d1-2856-47d9-9cfc-49214f515c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-2-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-105 ng-trigger ng-trigger-translateTab&quot;]/app-client-assign-by-employee[@class=&quot;tab-container ng-star-inserted&quot;]/div[@class=&quot;white-container&quot;]</value>
      <webElementGuid>1a042a71-865d-4752-8848-ebc2af6be918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-2-0']/div/app-client-assign-by-employee/div[4]</value>
      <webElementGuid>26795ada-a560-4b8c-9f4a-601bde5f129e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-client-assign-by-employee/div[4]</value>
      <webElementGuid>6451e923-0c08-4c50-9145-7ae5994b6c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Clients searchcancelGTGG Tester 3' or . = ' Clients searchcancelGTGG Tester 3')]</value>
      <webElementGuid>e9fc0644-caf1-4c23-858b-20e65134fd1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
