<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_By Client</name>
   <tag></tag>
   <elementGuidId>ac2a4078-ec18-41ae-ae4b-14dd0a29b0cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-tab-label-5-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-tab-label-5-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56ff124b-c5ad-4a4c-984d-b5267ad60ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>dee15210-2c63-42b4-a0d9-94b3d16efea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-ripple mat-tab-label mat-focus-indicator ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>831bbd72-c92e-429f-9221-5054ef506c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-tab-label-5-1</value>
      <webElementGuid>c0414314-8c3a-4397-a389-820bbdaf2fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9be2e887-074c-49c4-a99b-4e1896720940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>857ce9f0-6d40-4b2c-be0e-088f3690735d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fa46c48f-1f17-4b71-85ac-0bc9f5a3f1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>62020c47-129c-4c8d-8ebe-44229ed9c17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mat-tab-content-5-1</value>
      <webElementGuid>54c8c763-77ad-44bb-b9e8-ac11251ea4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>90d0f2c0-0a01-4480-9961-0889c1cb4e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b33de4e-cba2-43fd-9932-aa059e13da59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>By Client</value>
      <webElementGuid>978a1a58-abf3-4d75-a9d5-67ab72c688d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-label-5-1&quot;)</value>
      <webElementGuid>889541c0-1c99-4d88-bf92-7796c64d2719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-5-1']</value>
      <webElementGuid>ee42f3ed-c723-4287-9293-24f1cc2e87c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='By Employee'])[1]/following::div[1]</value>
      <webElementGuid>557f6a39-d0ba-4b1d-8e17-58b4f2f4dae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Unit'])[1]/following::div[12]</value>
      <webElementGuid>f86692f7-bc34-44b1-84bc-f7166f401b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employees'])[1]/preceding::div[4]</value>
      <webElementGuid>7d170212-96c2-44de-9a2c-9f3c3abb7bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>1642a4bb-057d-45c5-aec4-48107a6e217a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-tab-label-5-1' and (text() = 'By Client' or . = 'By Client')]</value>
      <webElementGuid>9f9a93dd-17b9-47c4-a0b7-fbec974f0cb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
