<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Employees column after assign</name>
   <tag></tag>
   <elementGuidId>463c18f7-3318-417d-a544-fae38c77eb58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-5-1']/div/app-client-assign-by-client/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e8c96d4-765d-43fd-a685-b3fae329c02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d20a4cdb-7c87-4973-a668-d5f8cc5946af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>f0a4553b-a3a7-4faf-ae4b-7d08c1f2d888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-container</value>
      <webElementGuid>24fea565-8609-4918-9009-0a4aed33e00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d7b0e2a5-62bd-4d9d-826c-fc71eadab5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>7901c724-89f3-4322-8f81-cdfa5f5b5007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Employees searchcancelGTGG tester 2</value>
      <webElementGuid>f823e0d0-2cdc-4079-883c-c492184ba0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-5-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-406 ng-trigger ng-trigger-translateTab&quot;]/app-client-assign-by-client[@class=&quot;tab-container ng-star-inserted&quot;]/div[@class=&quot;white-container&quot;]</value>
      <webElementGuid>af9462e0-1dce-4893-872f-f6565834898d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-5-1']/div/app-client-assign-by-client/div[4]</value>
      <webElementGuid>22503b27-bc8e-42de-9cff-1347714cd50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-client-assign-by-client/div[4]</value>
      <webElementGuid>0d3677e1-721d-40bb-ac9e-94be2da74278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Employees searchcancelGTGG tester 2' or . = ' Employees searchcancelGTGG tester 2')]</value>
      <webElementGuid>2158ff4e-50be-438c-9c44-1ec58898fe7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
