<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Employees column</name>
   <tag></tag>
   <elementGuidId>3e1232b4-0d8d-4b53-98c1-4f508f2ff259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='white-container'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'white-container' and (text() = ' Employees searchcancelGG TESTERGTGG tester 2' or . = ' Employees searchcancelGG TESTERGTGG tester 2')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d7555ee-95fa-413f-a653-e35b5e9efbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b642c5ea-5465-4be8-b0c7-9c74095b1893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxflex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>f84ff3f7-7095-4b86-88db-d8e99bac81a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-container</value>
      <webElementGuid>b54b6d01-4bf9-47a5-be4c-1bea010e7186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>dbb50ac9-7649-46ce-82dd-597241295554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-fx-flex.lt-lg</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>59735c19-7864-4e5c-acf0-c7af9200ce74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Employees searchcancelGG TESTERGTGG tester 2</value>
      <webElementGuid>18e0e6f1-4b6e-4adc-b9ba-ba58d03b64b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-5-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-406 ng-trigger ng-trigger-translateTab&quot;]/app-client-assign-by-client[@class=&quot;tab-container ng-star-inserted&quot;]/div[@class=&quot;white-container&quot;]</value>
      <webElementGuid>306b66b7-96c7-48fc-aec3-93c65b10f300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-5-1']/div/app-client-assign-by-client/div[4]</value>
      <webElementGuid>afd65a24-f53e-40ce-9af1-1ca6eed08d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-client-assign-by-client/div[4]</value>
      <webElementGuid>b83f32b3-66b2-4624-a0a6-664cb23ed4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Employees searchcancelGG TESTERGTGG tester 2' or . = ' Employees searchcancelGG TESTERGTGG tester 2')]</value>
      <webElementGuid>01cc2b1e-78c0-4310-af29-914fb302f171</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
