<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select org unit modal</name>
   <tag></tag>
   <elementGuidId>42f1b09c-2ec1-43b6-822d-30d23c27632c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>0e097954-b701-4295-8b05-ff3b06ca99c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4f2997d6-14bd-4ecf-880e-8a2d7906396b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d93249e6-bf00-45ab-b352-854e95d862ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c33-61 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>9e7c0ba0-bc7c-4f5e-834d-cfc70e12ed25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-2</value>
      <webElementGuid>e189d692-2db3-4a05-b632-b81518110427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>dada1e05-f9ed-443b-a0bf-91d383e0afdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-2</value>
      <webElementGuid>daa7f1d9-7d25-4bd3-ad6a-a4f38300ff06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an organization unitGG AutomationSelectCancel</value>
      <webElementGuid>61230d1a-d147-41b0-8859-9396da5926ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-2&quot;)</value>
      <webElementGuid>0a678324-efaa-4161-b704-5410b70965bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']</value>
      <webElementGuid>7975ba17-02ed-419c-a6aa-8cbf03e64099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/mat-dialog-container</value>
      <webElementGuid>6f562be0-f7ab-4ff1-a96c-245dfbd92145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>c6f32754-b24f-40d5-884a-ccf13545251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>66746547-a837-4fec-a9b5-62f4e3ed51e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-2' and (text() = 'Select an organization unitGG AutomationSelectCancel' or . = 'Select an organization unitGG AutomationSelectCancel')]</value>
      <webElementGuid>cc7a0c50-0f4f-446e-8712-f3ddd203a4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
