<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Promote to Admin</name>
   <tag></tag>
   <elementGuidId>72242fef-c075-4443-840f-74f61943b1bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[34]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-button-base.mat-menu-item.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Promote to Admin' or . = 'Promote to Admin')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf9f15e1-122e-4fc1-857e-80c669580f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>172b0098-38e9-418e-bb66-7cf7cca718a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipposition</name>
      <type>Main</type>
      <value>above</value>
      <webElementGuid>53ae4e07-ef3d-4db2-bdf7-02d360871d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>permission-type</name>
      <type>Main</type>
      <value>OU_USER_PROMOTE</value>
      <webElementGuid>4c3c4070-d3c7-4440-ae1a-8f1ea0865049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-button-base mat-menu-item ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>f3686eb6-4068-481e-b009-505532517cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-position</name>
      <type>Main</type>
      <value>above</value>
      <webElementGuid>1c684d68-a5b3-493c-b1d9-3ce765e76338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-permission-type</name>
      <type>Main</type>
      <value>OU_USER_PROMOTE</value>
      <webElementGuid>c40dee03-21a6-4ff8-8283-3d339f07086d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-message</name>
      <type>Main</type>
      <value>Promote to Admin</value>
      <webElementGuid>1d21c3fd-ce02-41c0-9d53-d2af5a3f4ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action-menu-desc</name>
      <type>Main</type>
      <value>Promote to Admin</value>
      <webElementGuid>9be4b9c6-95d3-4bb9-9aae-00edbd58823e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-665</value>
      <webElementGuid>d7e6f0e5-017c-439d-8776-69df555a8192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promote to Admin</value>
      <webElementGuid>67b8bdb4-853f-40ec-8925-6077772e85eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-621&quot;)/div[@class=&quot;mat-menu-content ng-tns-c98-980&quot;]/div[@class=&quot;ng-tns-c98-980&quot;]/button[@class=&quot;mat-focus-indicator mat-button-base mat-menu-item ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>c0e10fdf-b5ec-496b-9548-e393b40fedd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[34]</value>
      <webElementGuid>aa1de09d-b3d9-47c0-ac0f-9d77e70a7289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-621']/div/div/button[2]</value>
      <webElementGuid>10b2ed7a-3c9e-4138-bd21-dfbf86c1ee8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete User'])[1]/following::button[1]</value>
      <webElementGuid>b65e89f1-47da-42a6-b735-900c06381517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 6'])[1]/following::button[10]</value>
      <webElementGuid>891a968a-ede5-4e11-9b2e-31b36649761a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Role'])[1]/preceding::button[1]</value>
      <webElementGuid>8bec773f-dfc7-42d5-a416-6707ffbc17bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button[2]</value>
      <webElementGuid>a0a51562-6a08-412a-9db5-ae21470f8da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Promote to Admin' or . = 'Promote to Admin')]</value>
      <webElementGuid>9f1b1a13-9296-4766-beab-62d1b40b8fdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
