<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GG Automation</name>
   <tag></tag>
   <elementGuidId>d3b987ba-f7d0-4768-9ada-3074c8287fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div/div[3]/mat-drawer-container/mat-drawer/div/perfect-scrollbar/div/div/div/div[2]/ui-org-tree/section[2]/div[2]/tree-root/tree-viewport/div/div/tree-node-collection/div/tree-node/div/tree-node-wrapper/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.node-content-wrapper.node-content-wrapper-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7469b860-a6a8-4323-8687-8c823c346ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>node-content-wrapper node-content-wrapper-focused</value>
      <webElementGuid>b689c02f-cf7b-47ea-95b5-fc7159cb106f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tree-allow-drop</name>
      <type>Main</type>
      <value>(element, $event) => {
      </value>
      <webElementGuid>3793e3e3-866c-4d85-8f5b-409aaedec858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-allow-dragover-styling</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cfba873f-1772-40ae-bd09-47030fa8ceea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-dragged-element</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>47a9feb3-5733-4502-ac89-80b592a2fed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>16bff34a-ba39-4db6-a04b-b1255c2ea1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GG Automation</value>
      <webElementGuid>103d50b1-3e94-4d12-ab93-f6f8a43882db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c361-48 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;white-container ng-tns-c649-37&quot;]/div[@class=&quot;user-container-body ng-tns-c649-37&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container ng-tns-c649-37 mat-drawer-transition&quot;]/mat-drawer[@class=&quot;mat-drawer ng-tns-c192-38 ng-trigger ng-trigger-transform mat-drawer-end mat-drawer-side ng-star-inserted mat-drawer-opened&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c192-38&quot;]/perfect-scrollbar[@class=&quot;perfect-scrollbar ng-tns-c192-38&quot;]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/div[@class=&quot;table-option-container&quot;]/div[@class=&quot;org-tree-container ng-tns-c649-37&quot;]/ui-org-tree[@class=&quot;ng-tns-c649-37&quot;]/section[@class=&quot;section-org-tree-body&quot;]/div[@class=&quot;tree-wrapper&quot;]/tree-root[1]/tree-viewport[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;angular-tree-component&quot;]/tree-node-collection[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/tree-node[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;tree-node-level-1 tree-node tree-node-leaf ng-star-inserted tree-node-focused&quot;]/tree-node-wrapper[1]/div[@class=&quot;node-wrapper ng-star-inserted&quot;]/div[@class=&quot;node-content-wrapper node-content-wrapper-focused&quot;]</value>
      <webElementGuid>62ac9a52-0d4e-45a2-a0c8-c9809721da75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div/div[3]/mat-drawer-container/mat-drawer/div/perfect-scrollbar/div/div/div/div[2]/ui-org-tree/section[2]/div[2]/tree-root/tree-viewport/div/div/tree-node-collection/div/tree-node/div/tree-node-wrapper/div/div</value>
      <webElementGuid>0e4fe596-fb34-4ddc-85dd-dd3534835a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search here'])[1]/preceding::div[9]</value>
      <webElementGuid>75d8b06b-f92d-4eb3-af8e-06d5c2b9f0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tree-node-wrapper/div/div</value>
      <webElementGuid>c7b29520-be48-4736-b0a4-443ea491d129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'GG Automation' or . = 'GG Automation')]</value>
      <webElementGuid>799bf9c7-07c4-44c9-b1a7-ef15bee68595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
