<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_roleTypeDropdown</name>
   <tag></tag>
   <elementGuidId>b66b99c4-1d11-4c38-9e07-4d70ce89461b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@ng-reflect-ng-switch='false'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow-wrapper.ng-tns-c246-72</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acede679-d137-48d2-849f-aa371a1decb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow-wrapper ng-tns-c246-72</value>
      <webElementGuid>40920d31-97ad-4c6b-a002-93252e4321b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-1&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c246-72&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c246-72&quot;]</value>
      <webElementGuid>e6b8812b-1885-454d-bd1a-512f70de5b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-1']/div/div[2]</value>
      <webElementGuid>81cffafa-96a2-40c8-ba65-652e84907ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[1]/following::div[1]</value>
      <webElementGuid>72f81890-777d-41be-ad92-0b6da05b1aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning! Changing roles will remove user from any teams, channels and chats it is associated to.'])[1]/following::div[8]</value>
      <webElementGuid>1e9a07aa-c8fc-4af1-9fe0-9e63f513b0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Type'])[2]/preceding::div[2]</value>
      <webElementGuid>5ac0c72b-dd0e-4af3-a1c1-ad130e2fb6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[6]</value>
      <webElementGuid>fa65511a-72ec-41a6-9d4a-7fbd16527c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/mat-form-field/div/div/div/mat-select/div/div[2]</value>
      <webElementGuid>3fefe6b5-c77f-4ebc-aef0-251589ed6f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
