<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Reactivate User</name>
   <tag></tag>
   <elementGuidId>e2cc633f-bfe2-4bad-9478-23a4ae242aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4[@class = 'mat-dialog-title' and (text() = 'Reactivate User' or . = 'Reactivate User')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@class = 'mat-dialog-title' and (text() = 'Reactivate User' or . = 'Reactivate User')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>9da54712-9196-48c5-87ed-2b584e043a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>f390a410-0e5d-4f0b-b185-e4895909a78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-2</value>
      <webElementGuid>23d2db71-6427-488c-883f-1619043f74fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reactivate User</value>
      <webElementGuid>41f187e7-2eeb-4416-bc05-240db70e03b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-2&quot;)</value>
      <webElementGuid>f315a6d5-2e83-462e-8f4e-188b74c70ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-2']</value>
      <webElementGuid>19c67402-e83c-4713-ab55-8f7aff431ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']/app-dialog-suspend-user/section/div/h4</value>
      <webElementGuid>ed00614a-1ef7-4ae6-b3c5-4d1fce8a6a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-title-2', '&quot;', ')')])[1]/following::h4[1]</value>
      <webElementGuid>14911949-a4c9-42fa-a2e9-c1070761447f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h4[1]</value>
      <webElementGuid>da8ac488-a2e5-4cd6-9659-863bc9332a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to reactivate user ?'])[1]/preceding::h4[1]</value>
      <webElementGuid>f4a32ddb-102b-4ca4-a376-a895466d857b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reactivate'])[1]/preceding::h4[1]</value>
      <webElementGuid>dc656a44-9f1f-482e-a9e1-a70f362bcadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reactivate User']/parent::*</value>
      <webElementGuid>995c3889-41a1-44d7-93be-75c6b0b628ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/h4</value>
      <webElementGuid>39504e7d-180b-41ff-9c7b-6ecfc8a6c507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-2' and (text() = 'Reactivate User' or . = 'Reactivate User')]</value>
      <webElementGuid>2da18542-440e-4720-ad98-d324a3164f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
