<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Suspend User</name>
   <tag></tag>
   <elementGuidId>8446dbbe-2ee4-400a-817c-4728e3d65855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h4[@class = 'mat-dialog-title' and (text() = 'Suspend User' or . = 'Suspend User')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@class = 'mat-dialog-title' and (text() = 'Suspend User' or . = 'Suspend User')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f520364b-591f-4eee-b06e-853ca942099a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>64d811a0-9afb-4ec0-9bcb-5927e484b910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-1</value>
      <webElementGuid>270c529e-5ca3-4e45-b79a-8b0cceb4f7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suspend User</value>
      <webElementGuid>0d3e1831-1977-48e4-96ff-29c02647e9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-1&quot;)</value>
      <webElementGuid>3f4ee813-5f74-4217-a5a9-321f65dea7b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='mat-dialog-title-1']</value>
      <webElementGuid>3deea615-beb4-49dd-abd9-b6d0fec3ed5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/app-dialog-suspend-user/section/div/h4</value>
      <webElementGuid>58e3e7b5-02ca-4bf5-83fa-0c2f14d2a575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-title-1', '&quot;', ')')])[1]/following::h4[1]</value>
      <webElementGuid>1f44e11d-8fa0-4388-9a1a-fb78f02be515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h4[1]</value>
      <webElementGuid>58f4b295-ca48-46a2-bc4c-59ea93e541d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspend'])[1]/preceding::h4[1]</value>
      <webElementGuid>06ddcef4-1a2e-4736-8bae-2fb613c76e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suspend User']/parent::*</value>
      <webElementGuid>42c9190f-6b1c-4857-bd50-bd23d6b4680a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/h4</value>
      <webElementGuid>ba9cf84d-5649-4cbd-a490-fdbba4d04729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'mat-dialog-title-1' and (text() = 'Suspend User' or . = 'Suspend User')]</value>
      <webElementGuid>116fab2c-441d-4df2-a9b4-cbe76be73e5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
