<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_None</name>
   <tag></tag>
   <elementGuidId>ed928a58-1f5d-48b9-a455-8adfceb2ab32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()=' None ']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-option[@role = 'option' and (text() = ' None ' or . = ' None ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>2999fb98-faf1-4990-bace-98d7693585f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a6f49077-76a2-4868-ae45-e3a4b94daf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator ng-tns-c246-72 ng-star-inserted</value>
      <webElementGuid>9f496be8-587c-482e-91a6-6b521da86d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>ROLETYPE_NONE</value>
      <webElementGuid>4675e375-94ea-4fc3-8e83-b2595072ed64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-3</value>
      <webElementGuid>ed271d16-8290-43e4-8974-baae91ea06c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>271cbe59-b2a3-428f-a15a-28f182f5372e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01566a0b-062d-4b3a-aa5a-9b36c22eb54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> None </value>
      <webElementGuid>bbadedb9-4fa6-4f13-a5dd-89ea1f0af366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-3&quot;)</value>
      <webElementGuid>37880c0e-4399-4bca-9a41-00cf974b591b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-3']</value>
      <webElementGuid>545f8f9f-2ce1-40d5-bf01-4b4ae4579baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-1-panel']/mat-option[8]</value>
      <webElementGuid>884bcfad-e764-4923-a9cb-677caa3965c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/following::mat-option[1]</value>
      <webElementGuid>d0aceef1-16f6-4bff-83fb-1be05c5369fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT'])[2]/following::mat-option[2]</value>
      <webElementGuid>2be4a86b-2a09-4400-962e-93dc1bab1461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Quick Shortcuts'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>863ea104-35bc-4fef-bddc-e0c5361bf0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[8]</value>
      <webElementGuid>a2ab3149-8bb9-4b33-b62b-2cabca962e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-3' and (text() = ' None ' or . = ' None ')]</value>
      <webElementGuid>0cd88d7c-dc85-498e-9995-308c0d8e7d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
