<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_IT</name>
   <tag></tag>
   <elementGuidId>9ed2abab-e683-450c-b28e-6de31b33506f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-9</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-option[@role = 'option' and (text() = ' IT ' or . = ' IT ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>61ccb919-f60f-4a5c-93e6-faff38e3e808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b33b9ac4-ab5d-43ed-ba9f-9d40bd6ea3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator ng-tns-c246-72 ng-star-inserted</value>
      <webElementGuid>0730d5e9-f508-4c7c-ade5-4a6c6da6e5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>ROLETYPE_IT</value>
      <webElementGuid>bf1d2cc9-9f8b-471c-86f5-903b56589c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-9</value>
      <webElementGuid>14489769-7855-4fa2-813d-0a792951006e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a31ad54-ab48-420b-ba50-b3202b0075ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b5a1b5f-35a7-4e88-8871-a81349afcf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> IT </value>
      <webElementGuid>2211c7f8-ab70-4cdf-aa12-11e5cad98f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-9&quot;)</value>
      <webElementGuid>9c83b23e-09fd-4389-881a-6c828e1f4780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-9']</value>
      <webElementGuid>1c175c58-14c6-4b20-a607-0c76cc175532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-1-panel']/mat-option[6]</value>
      <webElementGuid>7b17e51e-1b97-4c0a-ba37-040e481fd575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Staff'])[1]/following::mat-option[1]</value>
      <webElementGuid>c064db1b-3e82-404c-9d63-762f697e5018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Human Resources'])[1]/following::mat-option[2]</value>
      <webElementGuid>5f7ff2b1-bcdc-421f-b974-ba2fdceeebe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>ffeba3f4-efb1-4431-a6ca-0be4dd8eb907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[6]</value>
      <webElementGuid>e700fe63-7176-4317-a7ef-d21484fc7363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-9' and (text() = ' IT ' or . = ' IT ')]</value>
      <webElementGuid>e72d6554-0937-42f8-b583-7713cb46cb7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
